In [ ]:
# Gini index: [0,0.5]
# Information Gain:[0,1]
# CART: Classification and regression Tree
# Decision Tree pruning: used to avoid overfitting

## Problem Statement: Identify either note is Genuine or not using predictive modelling  and with the help of Decision tree

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('banknotes.csv')
df.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
# lets Create input and output data
X = df.drop(columns='Class')
X[:3]

   Variance  Skewness  Curtosis  Entropy
0    3.6216    8.6661   -2.8073 -0.44699
1    4.5459    8.1674   -2.4586 -1.46210
2    3.8660   -2.6383    1.9242  0.10645

In [4]:
y = df['Class']
y[:3]

0    0
1    0
2    0
Name: Class, dtype: int64

In [5]:
# splitting the dataset
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2)

In [7]:
# Import Descision tree algo
#from sklearn.tree import DecisionTreeRegressor

# current problem is binary classification problem
# hence classifier wil be used
from sklearn.tree import DecisionTreeClassifier

In [8]:
model = DecisionTreeClassifier()

In [9]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
model.classes_

array([0, 1], dtype=int64)

In [11]:
# prediction
y_pred = model.predict(X_test)
y_pred[:5]

array([0, 1, 0, 1, 1], dtype=int64)

In [12]:
y_test[:5]

48      0
1201    1
425     0
1290    1
833     1
Name: Class, dtype: int64

In [13]:
# Lets check trianing data score
model.score(X_train,y_train)*100

100.0

In [14]:
model.score(X_test,y_test)*100

98.18181818181819

In [15]:
#performance metrics
from sklearn.metrics import confusion_matrix,classification_report

In [16]:
confusion_matrix(y_test,y_pred)

array([[147,   2],
       [  3, 123]], dtype=int64)

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       149
           1       0.98      0.98      0.98       126

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

In [18]:
model.criterion

'gini'

In [19]:
# LEst apply entropy
model2 = DecisionTreeClassifier(criterion='entropy')

In [20]:
model2.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [21]:
y_pred2 = model2.predict(X_test)

In [22]:
confusion_matrix(y_test,y_pred2)

array([[147,   2],
       [  2, 124]], dtype=int64)

In [23]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       149
           1       0.98      0.98      0.98       126

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

# Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score?

In [ ]:
cv_score = cross_val_score(model,X,y)
cv_score

In [ ]:
cv_score.mean()*100

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
cross_val_score(LogisticRegression(),X,y,cv=3).mean()*100

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
cross_val_score(GaussianNB(),X,y).mean()*100

In [ ]:
# we have 2 options: Stratified vs Kfold cross validation
[0,1,2,3,4,5,6,7]
Train: [1 2 3 5 6 7] | test: [0 4]
Train: [0 2 3 4 6 7] | test: [1 5]
Train: [0 1 3 4 5 7] | test: [2 6]
Train: [0 1 2 4 5 6] | test: [3 7]
StratifiedKFold done

Train: [2 3 4 5 6 7] | test: [0 1]
Train: [0 1 4 5 6 7] | test: [2 3]
Train: [0 1 2 3 6 7] | test: [4 5]
Train: [0 1 2 3 4 5] | test: [6 7]
KFold done

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [ ]:
X = np.array([
    [1,2,3,4],
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44],
    [51,52,53,54],
    [61,62,63,64],
    [71,72,73,74]
])

y = np.array([0,0,0,0,1,1,1,1])

In [ ]:
kf = KFold(n_splits=4)

In [ ]:
list(kf.split(X))

In [ ]:
skf = StratifiedKFold(n_splits=4)
list(skf.split(X,y))

In [ ]:
for train_index,test_index in skf.split(X,y):
    print(train_index,test_index)

In [ ]:
for train_index,test_index in skf.split(X,y):
    print(X[train_index],X[test_index])

In [ ]:
X

# DT visualization

In [ ]:
from sklearn import tree

In [ ]:
X = df.iloc[:,:-1]
X[:2]

In [ ]:
model

In [ ]:
text_representation = tree.export_text(model,feature_names=['Variance', 'Skewness', 'Curtosis', 'Entropy'])
print(text_representation)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig = plt.figure(figsize=(18,11))
_ = tree.plot_tree(model, 
                   feature_names=['Variance', 'Skewness', 'Curtosis', 'Entropy'],  
                   class_names=['Fake','Genuine'],
                   filled=True)
plt.savefig('sample.png')

In [ ]:
plt.figure(figsize=(12,12))
tree.plot_tree(model, fontsize=6)
plt.savefig('tree_high_dpi', dpi=100)

# Hyperparameter using GridSearch CV

In [ ]:
DecisionTreeClassifier()

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
pr_grid = {
    'criterion':['gini','entropy'],
    'splitter':['best','random'],
    'max_depth':[2,3,4,5,6,8],
    'min_samples_split':[2,3],
    'min_samples_leaf':[1,2],
    'min_weight_fraction_leaf':[0.0,0.5]
    }

In [ ]:
pr_grid

In [ ]:
"""
GridSearchCV(
    estimator,
    param_grid,
"""
out = GridSearchCV(DecisionTreeClassifier(),pr_grid)

In [ ]:
X[:2]

In [ ]:
y = df.Class
y[:2]

In [ ]:
out.fit(X,y)

In [ ]:
out.best_params_

In [ ]:
pr_grid

In [ ]:
out.best_estimator_

In [ ]:
final = DecisionTreeClassifier(criterion='entropy', max_depth=8, min_samples_split=3)

In [ ]:
final.fit(X,y)

In [ ]:
final.score(X,y)*100

## Module Interface : 
 

- dumps() – This function is called to serialize an object hierarchy.
- loads() – This function is called to de-serialize a data stream.

# Serialization

The pickle module is used for implementing binary protocols for serializing and de-serializing a Python object structure. 
 

Pickling: It is a process where a Python object hierarchy is converted into a byte stream. 
 
Unpickling: It is the inverse of Pickling process where a byte stream is converted into an object hierarchy.

In [ ]:
import pickle

In [ ]:
# save the DT_model to disk
filename = 'DT.pickle'
pickle.dump(final, open(filename, 'wb'))

# De Serialization

In [ ]:
# end user/testing  team/ client/ devops team will use pickled file
check = pickle.load(open('DT.h5','rb'))
check

In [ ]:
s = 'python'
k = ''
for i in s:
    k = i + k
print(k)

In [ ]:
s #-1,-2,-3,..-6

In [ ]:
for i in range(-1,- (len(s)+1),-1):
    print(s[i],end='')

In [ ]:
*
**
***
****
*****

In [ ]:
[print(i*'*') for i in range(1,6)]