In [ ]:
#Groupby
"""
A groupby operation involves some combination of splitting the object, 
applying a function, and combining the results. 
This can be used to group large amounts of data and compute operations on these groups.
"""

In [1]:
#Splitting or Aggregations or Fiteration or Transformation
import pandas as pd

In [2]:
ipl_data = {'Team': ['MI', 'MI', 'Devils', 'Devils', 'Kings',
   'CSK', 'CSK', 'CSK', 'MI', 'Royals', 'Royals', 'MI'],
   'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
   'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
   'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

      Team  Rank  Year  Points
0       MI     1  2014     876
1       MI     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5      CSK     4  2015     812
6      CSK     1  2016     756
7      CSK     1  2017     788
8       MI     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11      MI     2  2017     690

In [21]:
# select column
#df.Team
#df['Team']
#-------------------------
#df[['Team']]
#df[['Team',"Points"]]
#--------------------------
#df.loc[:,:]
#df.loc[:,['Year','Team']]
# access sequential columns
#df.loc[:,::3] #access team and point
#-------------------
#df.loc[:,'Rank':'Year']# stop is inclusive
#df.iloc[:,1::2]#access Rank and Points
#df.iloc[:,::-1]
#-------------------------
# access Team	Rank
df.drop(columns=['Year','Points'])

      Team  Rank
0       MI     1
1       MI     2
2   Devils     2
3   Devils     3
4    Kings     3
5      CSK     4
6      CSK     1
7      CSK     1
8       MI     2
9   Royals     4
10  Royals     1
11      MI     2

In [23]:
#i want the unique Team Names/find out total teams in dataset
# which teams are present
df['Team'].unique()

array(['MI', 'Devils', 'Kings', 'CSK', 'Royals'], dtype=object)

In [30]:
# How many total teams we have???
df.Team.unique()

array(['MI', 'Devils', 'Kings', 'CSK', 'Royals'], dtype=object)

In [27]:
df['Team'].unique().size

5

In [28]:
len(df['Team'].unique())

5

In [32]:
#find out the total count (teamwise)
df['Team'].value_counts()
# default order Descending

MI        4
CSK       3
Devils    2
Royals    2
Kings     1
Name: Team, dtype: int64

In [33]:
# get in ascending order
df['Team'].value_counts(ascending=True)

Kings     1
Devils    2
Royals    2
CSK       3
MI        4
Name: Team, dtype: int64

In [34]:
df

      Team  Rank  Year  Points
0       MI     1  2014     876
1       MI     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5      CSK     4  2015     812
6      CSK     1  2016     756
7      CSK     1  2017     788
8       MI     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11      MI     2  2017     690

In [36]:
df.dtypes

Team      object
Rank       int64
Year       int64
Points     int64
dtype: object

In [37]:
#Group DataFrame using a mapper or by a Series of columns.
df.groupby('Team')
#groupby on Team column

In [40]:
# typecast above: to get an output
list(df.groupby('Team'))

[('CSK',
    Team  Rank  Year  Points
  5  CSK     4  2015     812
  6  CSK     1  2016     756
  7  CSK     1  2017     788),
 ('Devils',
       Team  Rank  Year  Points
  2  Devils     2  2014     863
  3  Devils     3  2015     673),
 ('Kings',
      Team  Rank  Year  Points
  4  Kings     3  2014     741),
 ('MI',
     Team  Rank  Year  Points
  0    MI     1  2014     876
  1    MI     2  2015     789
  8    MI     2  2016     694
  11   MI     2  2017     690),
 ('Royals',
        Team  Rank  Year  Points
  9   Royals     4  2014     701
  10  Royals     1  2015     804)]

In [41]:
tm = df.groupby('Team')
tm

In [43]:
for i in tm:
    print(i,end='\n\n')

('CSK',   Team  Rank  Year  Points
5  CSK     4  2015     812
6  CSK     1  2016     756
7  CSK     1  2017     788)

('Devils',      Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673)

('Kings',     Team  Rank  Year  Points
4  Kings     3  2014     741)

('MI',    Team  Rank  Year  Points
0    MI     1  2014     876
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690)

('Royals',       Team  Rank  Year  Points
9   Royals     4  2014     701
10  Royals     1  2015     804)

In [45]:
import numpy as np
np.unique(df.Team) #follow alphabatic order

array(['CSK', 'Devils', 'Kings', 'MI', 'Royals'], dtype=object)

In [50]:
#if i want only team from a tuple
for i in tm:
    print(i[0],end='\n\n')

CSK

Devils

Kings

MI

Royals

In [51]:
#if i want only dataFrame of team from a tuple
for i in tm:
    print(i[1],end='\n\n')

  Team  Rank  Year  Points
5  CSK     4  2015     812
6  CSK     1  2016     756
7  CSK     1  2017     788

     Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673

    Team  Rank  Year  Points
4  Kings     3  2014     741

   Team  Rank  Year  Points
0    MI     1  2014     876
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690

      Team  Rank  Year  Points
9   Royals     4  2014     701
10  Royals     1  2015     804

In [56]:
#if i want only team/only data of each team from a tuple: Unpacking of a tuple
for team,data in tm:
    print(team,end='\n\n')

CSK

Devils

Kings

MI

Royals

In [61]:
#fetch data of only MI
for team,data in tm:
    if team  == 'MI':
        print(data)

   Team  Rank  Year  Points
0    MI     1  2014     876
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690

In [64]:
# without groupby normal solutions:fetch data of only MI
df[df.Team == 'MI']

   Team  Rank  Year  Points
0    MI     1  2014     876
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690

In [66]:
#to get same answer use query
df.query('Team == "MI"')

   Team  Rank  Year  Points
0    MI     1  2014     876
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690

In [71]:
#groups():it gives team name : index(where it is present)
df.groupby('Team').groups

{'CSK': [5, 6, 7], 'Devils': [2, 3], 'Kings': [4], 'MI': [0, 1, 8, 11], 'Royals': [9, 10]}

In [85]:
k = df.groupby('Team').groups
k

{'CSK': [5, 6, 7], 'Devils': [2, 3], 'Kings': [4], 'MI': [0, 1, 8, 11], 'Royals': [9, 10]}

In [89]:
d_ind = k['Devils']
d_ind

Int64Index([2, 3], dtype='int64')

In [90]:
df.loc[d_ind,:]

     Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673

In [98]:
print('Welcome to IPL SEARCH')
print('Select your team from below:')
print(k.keys())
tem = input('Enter your Team:')
ind = k[tem]
df.loc[ind,:]

Welcome to IPL SEARCH
Select your team from below:
dict_keys(['CSK', 'Devils', 'Kings', 'MI', 'Royals'])
Enter your Team:Kings

    Team  Rank  Year  Points
4  Kings     3  2014     741

In [100]:
list(df.groupby(['Team','Year']))

[(('CSK', 2015),
    Team  Rank  Year  Points
  5  CSK     4  2015     812),
 (('CSK', 2016),
    Team  Rank  Year  Points
  6  CSK     1  2016     756),
 (('CSK', 2017),
    Team  Rank  Year  Points
  7  CSK     1  2017     788),
 (('Devils', 2014),
       Team  Rank  Year  Points
  2  Devils     2  2014     863),
 (('Devils', 2015),
       Team  Rank  Year  Points
  3  Devils     3  2015     673),
 (('Kings', 2014),
      Team  Rank  Year  Points
  4  Kings     3  2014     741),
 (('MI', 2014),
    Team  Rank  Year  Points
  0   MI     1  2014     876),
 (('MI', 2015),
    Team  Rank  Year  Points
  1   MI     2  2015     789),
 (('MI', 2016),
    Team  Rank  Year  Points
  8   MI     2  2016     694),
 (('MI', 2017),
     Team  Rank  Year  Points
  11   MI     2  2017     690),
 (('Royals', 2014),
       Team  Rank  Year  Points
  9  Royals     4  2014     701),
 (('Royals', 2015),
        Team  Rank  Year  Points
  10  Royals     1  2015     804)]

In [10]:
#take sum of all points yearwise
#list(df.groupby('Year'))
out1 = df.groupby('Year')
#list(out1['Points'])
out1['Points'].sum()

Year
2014    3181
2015    3078
2016    1450
2017    1478
Name: Points, dtype: int64

In [18]:
#teamwise summation of Points
#df.groupby('Team')['Points'].sum()
ans = df.groupby('Team').sum()
ans.Points

Team
CSK       2356
Devils    1536
Kings      741
MI        3049
Royals    1505
Name: Points, dtype: int64

In [24]:
#fetch only teams with rank 1
#list(df.groupby('Rank'))
ans_2 = df.groupby('Rank').get_group(1)
ans_2.Team

0         MI
6        CSK
7        CSK
10    Royals
Name: Team, dtype: object

In [26]:
ans_2[['Team','Year']]

      Team  Year
0       MI  2014
6      CSK  2016
7      CSK  2017
10  Royals  2015

In [30]:
#fetch 1st entry of each category(rank) according to Team with Rank groupby
#list(df.groupby('Rank'))
df.groupby('Rank').first()
#last()

        Team  Year  Points
Rank
1         MI  2014     876
2         MI  2015     789
3     Devils  2015     673
4        CSK  2015     812

In [37]:
#list(df.groupby('Team'))
df.groupby('Team').first()

        Rank  Year  Points
Team
CSK        4  2015     812
Devils     2  2014     863
Kings      3  2014     741
MI         1  2014     876
Royals     4  2014     701

In [33]:
df.groupby('Team').last()
# teamwise last record

        Rank  Year  Points
Team
CSK        1  2017     788
Devils     3  2015     673
Kings      3  2014     741
MI         2  2017     690
Royals     1  2015     804

In [41]:
res = list(df.groupby('Team'))
for i,j in res:
    print(j.head(2))
    print()

  Team  Rank  Year  Points
5  CSK     4  2015     812
6  CSK     1  2016     756

     Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673

    Team  Rank  Year  Points
4  Kings     3  2014     741

  Team  Rank  Year  Points
0   MI     1  2014     876
1   MI     2  2015     789

      Team  Rank  Year  Points
9   Royals     4  2014     701
10  Royals     1  2015     804

In [43]:
#Multiple column groupby
list(df.groupby(['Team','Rank']))

[(('CSK', 1),
    Team  Rank  Year  Points
  6  CSK     1  2016     756
  7  CSK     1  2017     788),
 (('CSK', 4),
    Team  Rank  Year  Points
  5  CSK     4  2015     812),
 (('Devils', 2),
       Team  Rank  Year  Points
  2  Devils     2  2014     863),
 (('Devils', 3),
       Team  Rank  Year  Points
  3  Devils     3  2015     673),
 (('Kings', 3),
      Team  Rank  Year  Points
  4  Kings     3  2014     741),
 (('MI', 1),
    Team  Rank  Year  Points
  0   MI     1  2014     876),
 (('MI', 2),
     Team  Rank  Year  Points
  1    MI     2  2015     789
  8    MI     2  2016     694
  11   MI     2  2017     690),
 (('Royals', 1),
        Team  Rank  Year  Points
  10  Royals     1  2015     804),
 (('Royals', 4),
       Team  Rank  Year  Points
  9  Royals     4  2014     701)]

In [44]:
df.groupby(['Team','Rank']).get_group(('MI', 2))

   Team  Rank  Year  Points
1    MI     2  2015     789
8    MI     2  2016     694
11   MI     2  2017     690

In [ ]:
#i want record of year 2017
#assignment

In [56]:
# i want the team who stood 1st max times in ipl
fst = df.groupby('Rank').get_group(1)
team = fst.Team.value_counts()
team.nlargest(1)

CSK    2
Name: Team, dtype: int64

In [61]:
n = pd.DataFrame({'num':[980,100,300,280,30,160]})
n

   num
0  980
1  100
2  300
3  280
4   30
5  160

In [63]:
n.num.nlargest(3)

0    980
2    300
3    280
Name: num, dtype: int64

In [66]:
n.num.nsmallest(2)

4     30
1    100
Name: num, dtype: int64

In [67]:
n

   num
0  980
1  100
2  300
3  280
4   30
5  160

In [68]:
#Aggregations #sum mean median mode std
#Aggregations work only on Numeric fields
import numpy as np

grouped = df.groupby('Year')
grouped['Points']

In [69]:
list(df.groupby('Year')['Points'])

[(2014,
  0    876
  2    863
  4    741
  9    701
  Name: Points, dtype: int64),
 (2015,
  1     789
  3     673
  5     812
  10    804
  Name: Points, dtype: int64),
 (2016,
  6    756
  8    694
  Name: Points, dtype: int64),
 (2017,
  7     788
  11    690
  Name: Points, dtype: int64)]

In [71]:
points = df.groupby('Year')['Points']
points.agg(sum)

Year
2014    3181
2015    3078
2016    1450
2017    1478
Name: Points, dtype: int64

In [72]:
points.agg(np.sum)

Year
2014    3181
2015    3078
2016    1450
2017    1478
Name: Points, dtype: int64

In [75]:
#Applying Multiple Aggregation Functions at Once
#list(points)
points.sum()

Year
2014    3181
2015    3078
2016    1450
2017    1478
Name: Points, dtype: int64

In [77]:
points.agg([sum,min,max])

       sum  min  max
Year
2014  3181  701  876
2015  3078  673  812
2016  1450  694  756
2017  1478  690  788

In [85]:
df.describe()

            Rank         Year      Points
count  12.000000    12.000000   12.000000
mean    2.166667  2015.166667  765.583333
std     1.114641     1.114641   67.849376
min     1.000000  2014.000000  673.000000
25%     1.000000  2014.000000  699.250000
50%     2.000000  2015.000000  772.000000
75%     3.000000  2016.000000  806.000000
max     4.000000  2017.000000  876.000000

In [81]:
#here size is nothing but occurance
yr = df.groupby('Year')
yr

In [82]:
list(yr)

[(2014,
       Team  Rank  Year  Points
  0      MI     1  2014     876
  2  Devils     2  2014     863
  4   Kings     3  2014     741
  9  Royals     4  2014     701),
 (2015,
        Team  Rank  Year  Points
  1       MI     2  2015     789
  3   Devils     3  2015     673
  5      CSK     4  2015     812
  10  Royals     1  2015     804),
 (2016,
    Team  Rank  Year  Points
  6  CSK     1  2016     756
  8   MI     2  2016     694),
 (2017,
     Team  Rank  Year  Points
  7   CSK     1  2017     788
  11   MI     2  2017     690)]

In [84]:
yr.Team.agg(np.size)

Year
2014    4
2015    4
2016    2
2017    2
Name: Team, dtype: int64

## Transformation

In [86]:
#Transformation calling a function over the selected data
grouped = df.groupby('Team')
# write a function to add +500 points to each team
grouped

In [87]:
list(grouped)

[('CSK',
    Team  Rank  Year  Points
  5  CSK     4  2015     812
  6  CSK     1  2016     756
  7  CSK     1  2017     788),
 ('Devils',
       Team  Rank  Year  Points
  2  Devils     2  2014     863
  3  Devils     3  2015     673),
 ('Kings',
      Team  Rank  Year  Points
  4  Kings     3  2014     741),
 ('MI',
     Team  Rank  Year  Points
  0    MI     1  2014     876
  1    MI     2  2015     789
  8    MI     2  2016     694
  11   MI     2  2017     690),
 ('Royals',
        Team  Rank  Year  Points
  9   Royals     4  2014     701
  10  Royals     1  2015     804)]

In [89]:
grouped['Points'].transform(lambda x:x+500)

0     1376
1     1289
2     1363
3     1173
4     1241
5     1312
6     1256
7     1288
8     1194
9     1201
10    1304
11    1190
Name: Points, dtype: int64

In [93]:
df.Points

0     876
1     789
2     863
3     673
4     741
5     812
6     756
7     788
8     694
9     701
10    804
11    690
Name: Points, dtype: int64

In [ ]:
#list(df.groupby('Team')['Points'])
df.groupby('Team')['Points'].transform(lambda x:x+100)

In [ ]:
list(df.groupby('Team')['Rank'])

In [ ]:
# I want to give the +10 exxtra points to csk use transform
# I want to give extra +10 point only to the teams from year 2015