In [1]:
import numpy as np
import pandas as pd

In [2]:
d = pd.DataFrame([12,35,2.6,4.5,5.8,9.7])
d

      0
0  12.0
1  35.0
2   2.6
3   4.5
4   5.8
5   9.7

In [3]:
d.dtypes

0    float64
dtype: object

In [4]:
#at the time of creation of df,if we want to change data type
d = pd.DataFrame([12,35,2.6,4.5,5.8,9.7],dtype='int')
d

C:\Users\hakim\AppData\Local\Temp/ipykernel_14544/445161139.py:2: FutureWarning: In a future version, passing float-dtype values and an integer dtype to DataFrame will retain floating dtype if they cannot be cast losslessly (matching Series behavior). To retain the old behavior, use DataFrame(data).astype(dtype)
  d = pd.DataFrame([12,35,2.6,4.5,5.8,9.7],dtype='int')

    0
0  12
1  35
2   2
3   4
4   5
5   9

In [5]:
d.dtypes

0    int32
dtype: object

In [6]:
d
#pd.DataFrame(data,index,columns,dtype)

    0
0  12
1  35
2   2
3   4
4   5
5   9

## astype: used for explicite typecasting

In [ ]:
# SYntax:
Series.astype(data_type)
DataFrame.astype(data_type)

In [7]:
d.dtypes

0    int32
dtype: object

In [8]:
e = d.astype('float32')
e

      0
0  12.0
1  35.0
2   2.0
3   4.0
4   5.0
5   9.0

In [9]:
e.dtypes

0    float32
dtype: object

In [10]:
e #dtype is float

      0
0  12.0
1  35.0
2   2.0
3   4.0
4   5.0
5   9.0

In [11]:
e.astype('int32')

    0
0  12
1  35
2   2
3   4
4   5
5   9

In [12]:
df = pd.DataFrame({'Name':['A','B'],'Age':[20,30],'Salary':[35000,56000]})
df

  Name  Age  Salary
0    A   20   35000
1    B   30   56000

In [14]:
df[['Age','Salary']].astype('int')

   Age  Salary
0   20   35000
1   30   56000

In [17]:
df.astype('int') #i wont work bcz of name column which is object type

ValueError: invalid literal for int() with base 10: 'A'

# Conditional selection

In [18]:
d

    0
0  12
1  35
2   2
3   4
4   5
5   9

In [24]:
#if we apply some condition then it results in bool output
d > 3

       0
0   True
1   True
2  False
3   True
4   True
5   True

In [25]:
d[0]>3 #d[0] is a series

0     True
1     True
2    False
3     True
4     True
5     True
Name: 0, dtype: bool

In [28]:
#supply above boolean output as an index into d
d[d[0]>3]

    0
0  12
1  35
3   4
4   5
5   9

In [29]:
d[d>3]#using dataframe directly as an index
#NaN Not a number

      0
0  12.0
1  35.0
2   NaN
3   4.0
4   5.0
5   9.0

In [30]:
d

    0
0  12
1  35
2   2
3   4
4   5
5   9

In [31]:
#with NaN
pd.DataFrame([10,20,np.nan])

      0
0  10.0
1  20.0
2   NaN

In [32]:
#without NaN
pd.DataFrame([10,20,88])

    0
0  10
1  20
2  88

## where

In [33]:
d>3

       0
0   True
1   True
2  False
3   True
4   True
5   True

In [34]:
#Replace values where the condition is False.
d.where(d>3)

      0
0  12.0
1  35.0
2   NaN
3   4.0
4   5.0
5   9.0

In [35]:
d.where(d[0]>3)
#where the condition is false there u will get NaN

      0
0  12.0
1  35.0
2   NaN
3   4.0
4   5.0
5   9.0

In [36]:
d.where(d[0]>3,0) #if we want to fill other values instead of nan then 
#we can put like this
# so where the condition is False u will get 0

    0
0  12
1  35
2   0
3   4
4   5
5   9

In [38]:
d[0].mean()

11.166666666666666

In [39]:
d.where(d[0]>3,d[0].mean())

           0
0  12.000000
1  35.000000
2  11.166667
3   4.000000
4   5.000000
5   9.000000

In [40]:
round(12.545556,2)

12.55

In [41]:
ot = round(d[0].mean(),2)
d.where(d[0]>3,ot)

       0
0  12.00
1  35.00
2  11.17
3   4.00
4   5.00
5   9.00

In [44]:
d.where(d<3,-d)
# in above case we are trying to make values negative where condition is False

    0
0 -12
1 -35
2   2
3  -4
4  -5
5  -9

In [45]:
rn = np.random.rand(4,4)
f = pd.DataFrame(rn)
f

          0         1         2         3
0  0.838246  0.211243  0.351525  0.751537
1  0.558306  0.707885  0.990488  0.982578
2  0.873068  0.517069  0.144646  0.834219
3  0.934447  0.565740  0.509976  0.337620

In [46]:
f.where(f>0.5)

          0         1         2         3
0  0.838246       NaN       NaN  0.751537
1  0.558306  0.707885  0.990488  0.982578
2  0.873068  0.517069       NaN  0.834219
3  0.934447  0.565740  0.509976       NaN

In [47]:
f.where(f>0.5,-10)

          0          1          2          3
0  0.838246 -10.000000 -10.000000   0.751537
1  0.558306   0.707885   0.990488   0.982578
2  0.873068   0.517069 -10.000000   0.834219
3  0.934447   0.565740   0.509976 -10.000000

In [50]:
f.where(f>0.5,-f)

          0         1         2         3
0  0.838246 -0.211243 -0.351525  0.751537
1  0.558306  0.707885  0.990488  0.982578
2  0.873068  0.517069 -0.144646  0.834219
3  0.934447  0.565740  0.509976 -0.337620

In [51]:
k = [1,0,0,1,1,0,1]
k

[1, 0, 0, 1, 1, 0, 1]

In [54]:
s = pd.Series(k)
s.map({1:0,0:1})

0    0
1    1
2    1
3    0
4    0
5    1
6    0
dtype: int64

In [55]:
ar = np.array(k)
ar

array([1, 0, 0, 1, 1, 0, 1])

In [56]:
np.where(ar>0,0,1)

array([0, 1, 1, 0, 0, 1, 0])

In [57]:
fn = lambda x: 0 if x > 0 else 1

In [59]:
list(map(fn,k))

[0, 1, 1, 0, 0, 1, 0]

### mask

In [60]:
#mask is exactly opposite of where
#means mask will make NaN whre condition is True and will get Values wher condition is False
f

          0         1         2         3
0  0.838246  0.211243  0.351525  0.751537
1  0.558306  0.707885  0.990488  0.982578
2  0.873068  0.517069  0.144646  0.834219
3  0.934447  0.565740  0.509976  0.337620

In [62]:
f[1]>.5

0    False
1     True
2     True
3     True
Name: 1, dtype: bool

In [65]:
f[1].mask(f[1]>.5)

0    0.211243
1         NaN
2         NaN
3         NaN
Name: 1, dtype: float64

In [68]:
f[1].mask(f[1]>.5,other=-1)

0    0.211243
1   -1.000000
2   -1.000000
3   -1.000000
Name: 1, dtype: float64