# Data Preprocessing 

- Data preprocessing is a process of preparing the raw data and making it suitable for a machine learning model. It is the first and crucial step while creating a machine learning model.



- When creating a machine learning project, it is not always a case that we come across the clean and formatted data. 



- And while doing any operation with data, it is mandatory to clean it and put in a formatted way. So for this, we use data preprocessing task.

In [ ]:
price
10000
10k
Ten
Ten Thausand
10
10$
'10000'

# What is the need of Data Preprocessing?

o A real-world data generally contains noises, missing values, and maybe in an unusable format which cannot be directly used for machine learning models. 


o Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

#### It involves below steps:

    Getting the dataset
    Importing libraries
    Importing datasets
    Finding Missing Data
    Encoding Categorical Data
    Splitting dataset into training and test set
    Feature scaling

In [1]:
import numpy as np
import pandas as pd

In [4]:
#country , age and salary
data = [['India',np.nan,68000.0],  
    ['France',43.0,45000.0],  
 ['Germany',30.0, np.nan],  
 ['France' ,48.0, 65000.0], 
 [np.nan ,40.0, np. nan],  
 ['India' ,35.0, 58000.0],  
 ['Germany', np.nan ,53000.0],  
 ['France' ,49.0, 79000.0],  
 [np.nan, 50.0 ,np.nan],  
 ['France' ,np.nan, 77000.0]]

In [6]:
df = pd.DataFrame(data,columns=['country','age','salary'])
df

   country   age   salary
0    India   NaN  68000.0
1   France  43.0  45000.0
2  Germany  30.0      NaN
3   France  48.0  65000.0
4      NaN  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8      NaN  50.0      NaN
9   France   NaN  77000.0

In [7]:
#check null values
df.isna().sum()

country    2
age        3
salary     3
dtype: int64

In [8]:
df.isnull().sum()

country    2
age        3
salary     3
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  8 non-null      object
 1   age      7 non-null      float64
 2   salary   7 non-null      float64
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes

In [ ]:
#Assiggnment
# Plot the NaN present in your dataset

# Ways to handle missing data:

#### There are mainly two ways to handle missing data, which are:

- *By deleting the particular row:* The first way is used to commonly deal with null values. In this way, we just delete the specific row or column which consists of null values. But this way is not so efficient and removing data may lead to loss of information which will not give the accurate output.




- *By calculating the mean:* In this way, we will calculate the mean of that column or row which contains any missing value and will put it on the place of missing value. This strategy is useful for the features which have numeric data such as age, salary, year, etc. Here, we will use this approach.

#Using pandas which options are availabel to fill the missing entries:
ffill/pad, backfill/bfill
fillna()
dropna()

## Preprocessing using sklearn

In [10]:
#handling missing data (Replacing missing data with the mean value)  
# SimpleImputer
from sklearn.impute import SimpleImputer

In [11]:
#Create an object of SimpleImputer
s = SimpleImputer()
#['NA','missing',np.nan]

In [ ]:
The imputation strategy.
    Default strategy='mean'
    - If "mean", then replace missing values using the mean along
      each column. Can only be used with numeric data.
    - If "median", then replace missing values using the median along
      each column. Can only be used with numeric data.
    - If "most_frequent", then replace missing using the most frequent
      value along each column. Can be used with strings or numeric data.
      If there is more than one such value, only the smallest is returned.
    - If "constant", then replace missing values with fill_value. Can be
      used with strings or numeric data.

In [14]:
# select a column with numeric type
num  = df.select_dtypes(exclude='object')
num

    age   salary
0   NaN  68000.0
1  43.0  45000.0
2  30.0      NaN
3  48.0  65000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  53000.0
7  49.0  79000.0
8  50.0      NaN
9   NaN  77000.0

In [16]:
#Fitting imputer object to the independent variables x.   
s.fit(num)

SimpleImputer()

In [19]:
#fitting gives different information abt feature
s.n_features_in_

2

In [20]:
s.missing_values

nan

In [25]:
s.strategy

'mean'

In [22]:
num.mean()

age          42.142857
salary    63571.428571
dtype: float64

In [23]:
#Replacing missing data with the calculated mean value using transform
s.transform(num)

array([[4.21428571e+01, 6.80000000e+04],
       [4.30000000e+01, 4.50000000e+04],
       [3.00000000e+01, 6.35714286e+04],
       [4.80000000e+01, 6.50000000e+04],
       [4.00000000e+01, 6.35714286e+04],
       [3.50000000e+01, 5.80000000e+04],
       [4.21428571e+01, 5.30000000e+04],
       [4.90000000e+01, 7.90000000e+04],
       [5.00000000e+01, 6.35714286e+04],
       [4.21428571e+01, 7.70000000e+04]])

In [24]:
num

    age   salary
0   NaN  68000.0
1  43.0  45000.0
2  30.0      NaN
3  48.0  65000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  53000.0
7  49.0  79000.0
8  50.0      NaN
9   NaN  77000.0

In [26]:
# if we want to perform fit and transform together?
s.fit_transform(num)

array([[4.21428571e+01, 6.80000000e+04],
       [4.30000000e+01, 4.50000000e+04],
       [3.00000000e+01, 6.35714286e+04],
       [4.80000000e+01, 6.50000000e+04],
       [4.00000000e+01, 6.35714286e+04],
       [3.50000000e+01, 5.80000000e+04],
       [4.21428571e+01, 5.30000000e+04],
       [4.90000000e+01, 7.90000000e+04],
       [5.00000000e+01, 6.35714286e+04],
       [4.21428571e+01, 7.70000000e+04]])

# Encoding Categorical data:

- Categorical data is data which has some categories such as,  Country


- Since machine learning model completely works on mathematics and numbers, but if our dataset would have a categorical variable, then it may create trouble while building the model. So it is necessary to encode these categorical variables into numbers.

In [29]:
df.country.unique()

array(['India', 'France', 'Germany', nan], dtype=object)

In [30]:
# using replace
df.country.replace({'France':0,'India':1,'Germany':2})

0    1.0
1    0.0
2    2.0
3    0.0
4    NaN
5    1.0
6    2.0
7    0.0
8    NaN
9    0.0
Name: country, dtype: float64

In [31]:
# using map
df.country.map({'France':0,'India':1,'Germany':2})

0    1.0
1    0.0
2    2.0
3    0.0
4    NaN
5    1.0
6    2.0
7    0.0
8    NaN
9    0.0
Name: country, dtype: float64

In [32]:
df.country.fillna(method='pad')
# use SimpleImputer to replace missing entries in Country column

0      India
1     France
2    Germany
3     France
4     France
5      India
6    Germany
7     France
8     France
9     France
Name: country, dtype: object

# sklearn.preprocessing