In [1]:
import numpy as np
import pandas as pd

In [2]:
# dict of series
data={'Name':pd.Series(['Anju','Rimi','Amol','Amit','Shobha','Arnav','Abhi']),
       'Age':pd.Series([25,26,30,32,27,36,40]),
'Percentage':pd.Series([59.76,67.80,80,85,78.33,60,75])}

In [3]:
data

{'Name': 0      Anju
 1      Rimi
 2      Amol
 3      Amit
 4    Shobha
 5     Arnav
 6      Abhi
 dtype: object,
 'Age': 0    25
 1    26
 2    30
 3    32
 4    27
 5    36
 6    40
 dtype: int64,
 'Percentage': 0    59.76
 1    67.80
 2    80.00
 3    85.00
 4    78.33
 5    60.00
 6    75.00
 dtype: float64}

In [4]:
df=pd.DataFrame(data)
df

     Name  Age  Percentage
0    Anju   25       59.76
1    Rimi   26       67.80
2    Amol   30       80.00
3    Amit   32       85.00
4  Shobha   27       78.33
5   Arnav   36       60.00
6    Abhi   40       75.00

## Summary: and apply stat on df

In [5]:
df

     Name  Age  Percentage
0    Anju   25       59.76
1    Rimi   26       67.80
2    Amol   30       80.00
3    Amit   32       85.00
4  Shobha   27       78.33
5   Arnav   36       60.00
6    Abhi   40       75.00

In [6]:
df.sum()   #default axis=0 (output will be columnwise)

Name          AnjuRimiAmolAmitShobhaArnavAbhi
Age                                       216
Percentage                             505.89
dtype: object

In [7]:
df.sum(axis=0)

Name          AnjuRimiAmolAmitShobhaArnavAbhi
Age                                       216
Percentage                             505.89
dtype: object

In [8]:
df.sum(axis=1)  #axis=1 will give addition of Age and % column

C:\Users\hakim\AppData\Local\Temp/ipykernel_12200/1990662314.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.sum(axis=1)  #axis=1 will give addition of Age and % column

0     84.76
1     93.80
2    110.00
3    117.00
4    105.33
5     96.00
6    115.00
dtype: float64

In [12]:
df[['Age','Percentage']].sum(axis=1)

0     84.76
1     93.80
2    110.00
3    117.00
4    105.33
5     96.00
6    115.00
dtype: float64

In [16]:
# select a columns with numeric type
#df.select_dtypes(include=float)
num_columns = df.select_dtypes(exclude=object)
num_columns

   Age  Percentage
0   25       59.76
1   26       67.80
2   30       80.00
3   32       85.00
4   27       78.33
5   36       60.00
6   40       75.00

In [17]:
num_columns.sum(axis=1)

0     84.76
1     93.80
2    110.00
3    117.00
4    105.33
5     96.00
6    115.00
dtype: float64

In [11]:
25+59.76

84.75999999999999

#### if i want only single column and i want to perform sum()

In [18]:
df['Percentage'].sum() 
# it returns value

505.89

In [20]:
df[['Percentage']].sum()
#it returns output in the form of Series

Percentage    505.89
dtype: float64

In [21]:
# if i want to apply sum on both columns
df[['Age','Percentage']].sum()

Age           216.00
Percentage    505.89
dtype: float64

In [22]:
df.loc[:,['Age','Percentage']].sum()

Age           216.00
Percentage    505.89
dtype: float64

In [23]:
# give me the summation of starting 5 rows
df.loc[:4,['Age','Percentage']]

   Age  Percentage
0   25       59.76
1   26       67.80
2   30       80.00
3   32       85.00
4   27       78.33

In [24]:
df.loc[:4,['Age','Percentage']].sum()

Age           140.00
Percentage    370.89
dtype: float64

In [25]:
df.iloc[:5,1:]

   Age  Percentage
0   25       59.76
1   26       67.80
2   30       80.00
3   32       85.00
4   27       78.33

## mean()

In [26]:
#df['Age'].mean() 
# take mean of all columns
df.mean()

C:\Users\hakim\AppData\Local\Temp/ipykernel_12200/4056729095.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()

Age           30.857143
Percentage    72.270000
dtype: float64

In [28]:
#take mean of Age column
df['Age'].mean()

30.857142857142858

In [29]:
df.Age.mean()

30.857142857142858

In [30]:
df[['Percentage','Age']].mean()

Percentage    72.270000
Age           30.857143
dtype: float64

In [32]:
df.select_dtypes(include=['float64','int64'])

   Age  Percentage
0   25       59.76
1   26       67.80
2   30       80.00
3   32       85.00
4   27       78.33
5   36       60.00
6   40       75.00

## std()

In [34]:
num_columns.std()

Age           5.550633
Percentage    9.941631
dtype: float64

## mode()

## median()

## min()

## max()

## cumsum()

## cumprod()

# Summarizing Data

In [35]:
df

     Name  Age  Percentage
0    Anju   25       59.76
1    Rimi   26       67.80
2    Amol   30       80.00
3    Amit   32       85.00
4  Shobha   27       78.33
5   Arnav   36       60.00
6    Abhi   40       75.00

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      object
 1   Age         7 non-null      int64
 2   Percentage  7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 296.0+ bytes

In [37]:
#check dtype of each colum
df.dtypes

Name           object
Age             int64
Percentage    float64
dtype: object

## Descriptive summary

In [38]:
df.describe() #summarizes only numeric columns (default)

             Age  Percentage
count   7.000000    7.000000
mean   30.857143   72.270000
std     5.550633    9.941631
min    25.000000   59.760000
25%    26.500000   63.900000
50%    30.000000   75.000000
75%    34.000000   79.165000
max    40.000000   85.000000

In [40]:
stat = df.describe().T
stat

            count       mean       std    min   25%   50%     75%   max
Age           7.0  30.857143  5.550633  25.00  26.5  30.0  34.000  40.0
Percentage    7.0  72.270000  9.941631  59.76  63.9  75.0  79.165  85.0

In [42]:
stat[['mean','min','max']]

                 mean    min   max
Age         30.857143  25.00  40.0
Percentage  72.270000  59.76  85.0

In [43]:
# if i want to use describe on object/str
df.describe(include='O')

        Name
count      7
unique     7
top     Anju
freq       1

In [44]:
n = pd.DataFrame({'name':['A','B','C','C','C']})
n

  name
0    A
1    B
2    C
3    C
4    C

In [45]:
n.describe()

       name
count     5
unique    3
top       C
freq      3

In [46]:
df.Name

0      Anju
1      Rimi
2      Amol
3      Amit
4    Shobha
5     Arnav
6      Abhi
Name: Name, dtype: object

In [47]:
#all columns i want
df.describe(include='all')

        Name        Age  Percentage
count      7   7.000000    7.000000
unique     7        NaN         NaN
top     Anju        NaN         NaN
freq       1        NaN         NaN
mean     NaN  30.857143   72.270000
std      NaN   5.550633    9.941631
min      NaN  25.000000   59.760000
25%      NaN  26.500000   63.900000
50%      NaN  30.000000   75.000000
75%      NaN  34.000000   79.165000
max      NaN  40.000000   85.000000

In [ ]:
# NaN: Not a Number==> missing data