## Manipulation of DataFrame: How to add rows

In [1]:
import pandas as pd

In [2]:
# List of Tuples
students = [ ('jack', 34, 'Sydeny' , 'Australia') ,
             ('Riti', 30, 'Delhi' , 'India' ) ,
             ('Vikas', 31, 'Mumbai' , 'India' ) ,
             ('Neelu', 32, 'Bangalore' , 'India' ) ,
             ('John', 16, 'New York' , 'US') ,
             ('Mike', 17, 'las vegas' , 'US')  ]

In [3]:
students

[('jack', 34, 'Sydeny', 'Australia'),
 ('Riti', 30, 'Delhi', 'India'),
 ('Vikas', 31, 'Mumbai', 'India'),
 ('Neelu', 32, 'Bangalore', 'India'),
 ('John', 16, 'New York', 'US'),
 ('Mike', 17, 'las vegas', 'US')]

In [4]:
#Create a DataFrame object
df = pd.DataFrame(students, columns = ['Name' , 'Age', 'City' , 'Country'], index=['a', 'b', 'c' , 'd' , 'e' , 'f']) 
df

    Name  Age       City    Country
a   jack   34     Sydeny  Australia
b   Riti   30      Delhi      India
c  Vikas   31     Mumbai      India
d  Neelu   32  Bangalore      India
e   John   16   New York         US
f   Mike   17  las vegas         US

### using dataframe.append() and Dictionary

In [5]:
df.head(2)

   Name  Age    City    Country
a  jack   34  Sydeny  Australia
b  Riti   30   Delhi      India

In [6]:
# Pass the row elements as key value pairs to append() function 
modDfObj = df.append({'Name' : 'Sunil' , 'Age' : 22} )
modDfObj

TypeError: Can only append a dict if ignore_index=True

In [9]:
modDfObj = df.append({'Name' : 'Sunil' , 'Age' : 22} , ignore_index=True)
modDfObj

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6  Sunil   22        NaN        NaN

In [10]:
modDfObj = df.append({'Name' : 'Sunil' , 'Age' : 22,'pincode':123456} , ignore_index=True)
modDfObj

    Name  Age       City    Country   pincode
0   jack   34     Sydeny  Australia       NaN
1   Riti   30      Delhi      India       NaN
2  Vikas   31     Mumbai      India       NaN
3  Neelu   32  Bangalore      India       NaN
4   John   16   New York         US       NaN
5   Mike   17  las vegas         US       NaN
6  Sunil   22        NaN        NaN  123456.0

### dataframe.append() and Series

In [11]:
s = pd.Series(['Raju', 21, 'Bangalore', 'India'],index=['Name','Age','City','Country'] )
s

Name            Raju
Age               21
City       Bangalore
Country        India
dtype: object

In [12]:
# Pass a series in append() to append a row in dataframe  ---#df.columns
modDfObj = df.append(s, 
                     ignore_index=True)
modDfObj

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6   Raju   21  Bangalore      India

In [13]:
r = pd.Series(['Rohit',23,'Paris','US'])
r

0    Rohit
1       23
2    Paris
3       US
dtype: object

In [14]:
df.append(r,ignore_index=True)

    Name   Age       City    Country      0     1      2    3
0   jack  34.0     Sydeny  Australia    NaN   NaN    NaN  NaN
1   Riti  30.0      Delhi      India    NaN   NaN    NaN  NaN
2  Vikas  31.0     Mumbai      India    NaN   NaN    NaN  NaN
3  Neelu  32.0  Bangalore      India    NaN   NaN    NaN  NaN
4   John  16.0   New York         US    NaN   NaN    NaN  NaN
5   Mike  17.0  las vegas         US    NaN   NaN    NaN  NaN
6    NaN   NaN        NaN        NaN  Rohit  23.0  Paris   US

In [15]:
r = pd.Series(['Rohit',23,'Paris','US'],index=['Name','Age','City','Country'])
r

Name       Rohit
Age           23
City       Paris
Country       US
dtype: object

In [16]:
df.append(r,ignore_index=True)

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6  Rohit   23      Paris         US

### Add multiple rows

In [17]:
df.columns

Index(['Name', 'Age', 'City', 'Country'], dtype='object')

In [18]:
pd.Series(['Raju', 21, 'Bangalore', 'India'],index=df.columns)#['Name']

Name            Raju
Age               21
City       Bangalore
Country        India
dtype: object

In [19]:
# List of series  
listOfSeries = [pd.Series(['Raju', 21, 'Bangalore', 'India'], index=df.columns ) ,
                pd.Series(['Sam', 22, 'Tokyo', 'Japan'], index=df.columns ) ,
                pd.Series(['Rocky', 23, 'Las Vegas', 'US'], index=df.columns ) ]
listOfSeries

[Name            Raju
 Age               21
 City       Bangalore
 Country        India
 dtype: object,
 Name         Sam
 Age           22
 City       Tokyo
 Country    Japan
 dtype: object,
 Name           Rocky
 Age               23
 City       Las Vegas
 Country           US
 dtype: object]

In [20]:
# Pass a list of series to the append() to add multiple rows
modDfObj = df.append(listOfSeries)
modDfObj

    Name  Age       City    Country
a   jack   34     Sydeny  Australia
b   Riti   30      Delhi      India
c  Vikas   31     Mumbai      India
d  Neelu   32  Bangalore      India
e   John   16   New York         US
f   Mike   17  las vegas         US
0   Raju   21  Bangalore      India
1    Sam   22      Tokyo      Japan
2  Rocky   23  Las Vegas         US

In [21]:
df

    Name  Age       City    Country
a   jack   34     Sydeny  Australia
b   Riti   30      Delhi      India
c  Vikas   31     Mumbai      India
d  Neelu   32  Bangalore      India
e   John   16   New York         US
f   Mike   17  las vegas         US

In [22]:
modDfObj = df.append(listOfSeries , ignore_index=True)
modDfObj

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6   Raju   21  Bangalore      India
7    Sam   22      Tokyo      Japan
8  Rocky   23  Las Vegas         US

### Add a row from one dataframe to other datafram

In [23]:
# List of Tuples
students = [ ('Rahul', 22, 'Sydeny' , 'Australia') ,
             ('Parul', 23, 'Pune' , 'India')  ]
#Create a DataFrame object
df2 = pd.DataFrame(students, columns = df.columns, index=['a', 'b']) 
df2

    Name  Age    City    Country
a  Rahul   22  Sydeny  Australia
b  Parul   23    Pune      India

In [24]:
df

    Name  Age       City    Country
a   jack   34     Sydeny  Australia
b   Riti   30      Delhi      India
c  Vikas   31     Mumbai      India
d  Neelu   32  Bangalore      India
e   John   16   New York         US
f   Mike   17  las vegas         US

In [26]:
modDfobj = df.append(df2, ignore_index=True)
modDfobj

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6  Rahul   22     Sydeny  Australia
7  Parul   23       Pune      India

In [30]:
df2.loc[['b'],:]

    Name  Age  City Country
b  Parul   23  Pune   India

In [31]:
# add row at index b from dataframe df2 to dataframe dfObj
modDfobj = df.append(df2.loc['b'], ignore_index=True)
modDfobj

    Name  Age       City    Country
0   jack   34     Sydeny  Australia
1   Riti   30      Delhi      India
2  Vikas   31     Mumbai      India
3  Neelu   32  Bangalore      India
4   John   16   New York         US
5   Mike   17  las vegas         US
6  Parul   23       Pune      India

In [32]:
df2[:1]

    Name  Age    City    Country
a  Rahul   22  Sydeny  Australia

In [40]:
#df2[:1]
#df2.head(1)
#df2.loc[['a']]
df2.iloc[[0]]

    Name  Age    City    Country
a  Rahul   22  Sydeny  Australia

In [34]:
df.head(3).append(df2[:1],ignore_index=True)

    Name  Age    City    Country
0   jack   34  Sydeny  Australia
1   Riti   30   Delhi      India
2  Vikas   31  Mumbai      India
3  Rahul   22  Sydeny  Australia

In [ ]:
df2[:1].append(df,ignore_index=True)

## without append how to add rows

In [41]:
df

    Name  Age       City    Country
a   jack   34     Sydeny  Australia
b   Riti   30      Delhi      India
c  Vikas   31     Mumbai      India
d  Neelu   32  Bangalore      India
e   John   16   New York         US
f   Mike   17  las vegas         US

In [43]:
# Add a new row at index k with values provided in list
df.loc['g'] = ['Smriti', 26, 'Bangalore', 'India']
df

     Name  Age       City    Country
a    jack   34     Sydeny  Australia
b    Riti   30      Delhi      India
c   Vikas   31     Mumbai      India
d   Neelu   32  Bangalore      India
e    John   16   New York         US
f    Mike   17  las vegas         US
g  Smriti   26  Bangalore      India

In [44]:
#if index is already present, at the same indeex
#if we want to add new data,then it will overwrite data
df.loc['e'] = ['Pravin', 26, 'Pune', 'India']
df

     Name  Age       City    Country
a    jack   34     Sydeny  Australia
b    Riti   30      Delhi      India
c   Vikas   31     Mumbai      India
d   Neelu   32  Bangalore      India
e  Pravin   26       Pune      India
f    Mike   17  las vegas         US
g  Smriti   26  Bangalore      India

In [45]:
df.loc['e']

Name       Pravin
Age            26
City         Pune
Country     India
Name: e, dtype: object

In [46]:
df.iloc[2]

Name        Vikas
Age            31
City       Mumbai
Country     India
Name: c, dtype: object

In [47]:
# Add a new row at index position 2 with values provided in list
df.iloc[2] = ['Mukesh', 22, 'Chennai', 'India']
df

     Name  Age       City    Country
a    jack   34     Sydeny  Australia
b    Riti   30      Delhi      India
c  Mukesh   22    Chennai      India
d   Neelu   32  Bangalore      India
e  Pravin   26       Pune      India
f    Mike   17  las vegas         US
g  Smriti   26  Bangalore      India

In [ ]:
#Assignment: I want to add entries/rows in between the present data frame
# NOTE: I dont want to overwrite data

## Addition of columns

In [48]:
df = df[:7]
df

     Name  Age       City    Country
a    jack   34     Sydeny  Australia
b    Riti   30      Delhi      India
c  Mukesh   22    Chennai      India
d   Neelu   32  Bangalore      India
e  Pravin   26       Pune      India
f    Mike   17  las vegas         US
g  Smriti   26  Bangalore      India

In [49]:
df.shape

(7, 4)

In [51]:
# to add column use df[column_name] = [values]
df['Number']=[1,2,3,4,5,7,8]

C:\Users\hakim\AppData\Local\Temp/ipykernel_4032/885231787.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Number']=[1,2,3,4,5,7,8]

In [52]:
df

     Name  Age       City    Country  Number
a    jack   34     Sydeny  Australia       1
b    Riti   30      Delhi      India       2
c  Mukesh   22    Chennai      India       3
d   Neelu   32  Bangalore      India       4
e  Pravin   26       Pune      India       5
f    Mike   17  las vegas         US       7
g  Smriti   26  Bangalore      India       8

In [53]:
import numpy as np
np.random.random(7)

array([0.05946776, 0.19545132, 0.48651496, 0.64740425, 0.86021131,
       0.09222407, 0.71835066])

In [54]:
df['Random']=np.random.random(7)

C:\Users\hakim\AppData\Local\Temp/ipykernel_4032/308598842.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Random']=np.random.random(7)

In [55]:
df

     Name  Age       City    Country  Number    Random
a    jack   34     Sydeny  Australia       1  0.910779
b    Riti   30      Delhi      India       2  0.120156
c  Mukesh   22    Chennai      India       3  0.681626
d   Neelu   32  Bangalore      India       4  0.305457
e  Pravin   26       Pune      India       5  0.318658
f    Mike   17  las vegas         US       7  0.241825
g  Smriti   26  Bangalore      India       8  0.936251

In [56]:
df.loc[:,['New_col']] = [10,20,30,40,50,60,70]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [57]:
df

     Name  Age       City    Country  Number    Random  New_col
a    jack   34     Sydeny  Australia       1  0.910779       10
b    Riti   30      Delhi      India       2  0.120156       20
c  Mukesh   22    Chennai      India       3  0.681626       30
d   Neelu   32  Bangalore      India       4  0.305457       40
e  Pravin   26       Pune      India       5  0.318658       50
f    Mike   17  las vegas         US       7  0.241825       60
g  Smriti   26  Bangalore      India       8  0.936251       70

In [58]:
# how to replace old values with new one
df.Number

a    1
b    2
c    3
d    4
e    5
f    7
g    8
Name: Number, dtype: int64

In [61]:
list(range(101,108))

[101, 102, 103, 104, 105, 106, 107]

In [67]:
df.Number = range(101,108)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [68]:
df

     Name  Age       City    Country  Number    Random  New_col
a    jack   34     Sydeny  Australia     101  0.910779       10
b    Riti   30      Delhi      India     102  0.120156       20
c  Mukesh   22    Chennai      India     103  0.681626       30
d   Neelu   32  Bangalore      India     104  0.305457       40
e  Pravin   26       Pune      India     105  0.318658       50
f    Mike   17  las vegas         US     106  0.241825       60
g  Smriti   26  Bangalore      India     107  0.936251       70

In [71]:
n = pd.Series(np.nan,index=range(7))
n

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
dtype: float64

In [73]:
df['NaN'] = n

C:\Users\hakim\AppData\Local\Temp/ipykernel_4032/397911752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NaN'] = n

In [74]:
df

     Name  Age       City    Country  Number    Random  New_col  NaN
a    jack   34     Sydeny  Australia     101  0.910779       10  NaN
b    Riti   30      Delhi      India     102  0.120156       20  NaN
c  Mukesh   22    Chennai      India     103  0.681626       30  NaN
d   Neelu   32  Bangalore      India     104  0.305457       40  NaN
e  Pravin   26       Pune      India     105  0.318658       50  NaN
f    Mike   17  las vegas         US     106  0.241825       60  NaN
g  Smriti   26  Bangalore      India     107  0.936251       70  NaN

In [ ]:
#assignment:
# How to add column in between the dataFrame
# How to change name of column which is already present 
# Replace Smriti as Snehal
# Replace Bangalore by Maysor

## Delete

In [75]:
df

     Name  Age       City    Country  Number    Random  New_col  NaN
a    jack   34     Sydeny  Australia     101  0.910779       10  NaN
b    Riti   30      Delhi      India     102  0.120156       20  NaN
c  Mukesh   22    Chennai      India     103  0.681626       30  NaN
d   Neelu   32  Bangalore      India     104  0.305457       40  NaN
e  Pravin   26       Pune      India     105  0.318658       50  NaN
f    Mike   17  las vegas         US     106  0.241825       60  NaN
g  Smriti   26  Bangalore      India     107  0.936251       70  NaN

In [76]:
# suppose we want to delete a column
del df['Number']

In [77]:
df

     Name  Age       City    Country    Random  New_col  NaN
a    jack   34     Sydeny  Australia  0.910779       10  NaN
b    Riti   30      Delhi      India  0.120156       20  NaN
c  Mukesh   22    Chennai      India  0.681626       30  NaN
d   Neelu   32  Bangalore      India  0.305457       40  NaN
e  Pravin   26       Pune      India  0.318658       50  NaN
f    Mike   17  las vegas         US  0.241825       60  NaN
g  Smriti   26  Bangalore      India  0.936251       70  NaN

In [81]:
del df['NaN']

In [87]:
df

     Name  Age       City    Country    Random  New_col
a    jack   34     Sydeny  Australia  0.910779       10
b    Riti   30      Delhi      India  0.120156       20
c  Mukesh   22    Chennai      India  0.681626       30
d   Neelu   32  Bangalore      India  0.305457       40
e  Pravin   26       Pune      India  0.318658       50
f    Mike   17  las vegas         US  0.241825       60
g  Smriti   26  Bangalore      India  0.936251       70

In [85]:
del df.Random #not allowed use [] option

AttributeError: Random

In [86]:
df.pop()

TypeError: pop() missing 1 required positional argument: 'item'

In [88]:
#Return item and drop from frame. Raise KeyError if not found.
df.pop('Age')

a    34
b    30
c    22
d    32
e    26
f    17
g    26
Name: Age, dtype: int64

In [89]:
df # df with no Age column

     Name       City    Country    Random  New_col
a    jack     Sydeny  Australia  0.910779       10
b    Riti      Delhi      India  0.120156       20
c  Mukesh    Chennai      India  0.681626       30
d   Neelu  Bangalore      India  0.305457       40
e  Pravin       Pune      India  0.318658       50
f    Mike  las vegas         US  0.241825       60
g  Smriti  Bangalore      India  0.936251       70

In [ ]:
# Assignments:
#How to delete a single row
#how to delete collection of rows
#how to delete random rows

In [93]:
df.Country['f'] = 'UK'

C:\Users\hakim\AppData\Local\Temp/ipykernel_4032/3302047950.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Country['f'] = 'UK'

In [94]:
df

     Name       City    Country    Random  New_col
a    jack     Sydeny  Australia  0.910779       10
b    Riti      Delhi      India  0.120156       20
c  Mukesh    Chennai      India  0.681626       30
d   Neelu  Bangalore      India  0.305457       40
e  Pravin       Pune      India  0.318658       50
f    Mike  las vegas         UK  0.241825       60
g  Smriti  Bangalore      India  0.936251       70

In [97]:
df.Country = df.Country.replace(['UK'],'YK')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [98]:
df

     Name       City    Country    Random  New_col
a    jack     Sydeny  Australia  0.910779       10
b    Riti      Delhi      India  0.120156       20
c  Mukesh    Chennai      India  0.681626       30
d   Neelu  Bangalore      India  0.305457       40
e  Pravin       Pune      India  0.318658       50
f    Mike  las vegas         YK  0.241825       60
g  Smriti  Bangalore      India  0.936251       70

In [99]:
df.dtypes

Name        object
City        object
Country     object
Random     float64
New_col      int64
dtype: object

In [102]:
df.Country.str.replace('YK','US')

a    Australia
b        India
c        India
d        India
e        India
f           US
g        India
Name: Country, dtype: object

In [104]:
df.Country = df.Country.str.replace('YK','US')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [105]:
df

     Name       City    Country    Random  New_col
a    jack     Sydeny  Australia  0.910779       10
b    Riti      Delhi      India  0.120156       20
c  Mukesh    Chennai      India  0.681626       30
d   Neelu  Bangalore      India  0.305457       40
e  Pravin       Pune      India  0.318658       50
f    Mike  las vegas         US  0.241825       60
g  Smriti  Bangalore      India  0.936251       70