In [1]:
import numpy as np
import pandas as pd

## query

In [ ]:
#Query using df

df = pd.DataFrame({'A': range(1, 6),
                   'B': range(10, 0, -2),
                   'C': range(10, 15)})
df

In [ ]:
#Query the columns of a DataFrame with a boolean expression
df.query('A > B')

In [ ]:
df.query('A==3')

In [ ]:
df[df['A']==3]

In [ ]:
#fetch the value from column B where value of column A==3
#df[df.A==3].B
#df[df.A==3]['B']
df[df.A==3][['B']]

In [ ]:
#fetch columb B where A is 3
df.query('A==3').B

In [ ]:
#fetch B and C where A==3
df.query('A==3')[['B','C']]

In [ ]:
df[df.A == 3][['B','C']]

In [ ]:
df

In [ ]:
df #if we want to do the addition of any two columns

In [ ]:
df['A']+df['B']

In [ ]:
pd.eval('df.A+df.B')

In [ ]:
df.eval('A+C')

# ---------Simple Data science Case study-------

In [2]:
df = pd.DataFrame({'name':['Ashwin','Sanjay','Smita','Vaibhav','Abhijeet','Mahesh','Supriya','Pallavi','Sumit','Chinu','Subhash'],
                  'place':['Pune','Satara','Sangli','Solapur','Kolhapur','Pune','Satara','Sangli','Solapur','Pune','Satara'],
                  'age':[42,20,25,36,28,24,45,25,21,19,45]})
df

        name     place  age
0     Ashwin      Pune   42
1     Sanjay    Satara   20
2      Smita    Sangli   25
3    Vaibhav   Solapur   36
4   Abhijeet  Kolhapur   28
5     Mahesh      Pune   24
6    Supriya    Satara   45
7    Pallavi    Sangli   25
8      Sumit   Solapur   21
9      Chinu      Pune   19
10   Subhash    Satara   45

In [12]:
#How many records are there?
#records means no. rows
df.shape

(11, 3)

In [14]:
df.age.mean()

30.0

In [28]:
# List out the names of employee
#df.name
#df['name']
#df[['name']]
df.loc[:,['name']]

        name
0     Ashwin
1     Sanjay
2      Smita
3    Vaibhav
4   Abhijeet
5     Mahesh
6    Supriya
7    Pallavi
8      Sumit
9      Chinu
10   Subhash

In [32]:
# i want list of names
print(list(df.name))

['Ashwin', 'Sanjay', 'Smita', 'Vaibhav', 'Abhijeet', 'Mahesh', 'Supriya', 'Pallavi', 'Sumit', 'Chinu', 'Subhash']

In [35]:
print(df.name.to_list())

['Ashwin', 'Sanjay', 'Smita', 'Vaibhav', 'Abhijeet', 'Mahesh', 'Supriya', 'Pallavi', 'Sumit', 'Chinu', 'Subhash']

In [37]:
# i want name column in array
df.name.values

array(['Ashwin', 'Sanjay', 'Smita', 'Vaibhav', 'Abhijeet', 'Mahesh',
       'Supriya', 'Pallavi', 'Sumit', 'Chinu', 'Subhash'], dtype=object)

In [38]:
np.array(df.name)

array(['Ashwin', 'Sanjay', 'Smita', 'Vaibhav', 'Abhijeet', 'Mahesh',
       'Supriya', 'Pallavi', 'Sumit', 'Chinu', 'Subhash'], dtype=object)

In [40]:
df.name.to_numpy()

array(['Ashwin', 'Sanjay', 'Smita', 'Vaibhav', 'Abhijeet', 'Mahesh',
       'Supriya', 'Pallavi', 'Sumit', 'Chinu', 'Subhash'], dtype=object)

In [44]:
#List out the names of columns
df.columns

Index(['name', 'place', 'age'], dtype='object')

In [47]:
# Change a column nm 'name' to 'Name'
df.rename(columns={'name':'Name'},inplace=True)

In [63]:
df

        name     place  age
0     Ashwin      Pune   42
1     Sanjay    Satara   20
2      Smita    Sangli   25
3    Vaibhav   Solapur   36
4   Abhijeet  Kolhapur   28
5     Mahesh      Pune   24
6    Supriya    Satara   45
7    Pallavi    Sangli   25
8      Sumit   Solapur   21
9      Chinu      Pune   19
10   Subhash    Satara   45

In [56]:
# i want to change all column names
df.columns = ['col_1','col2','col3']
#its default inplace

In [60]:
df.columns = ['name','place','age']

In [61]:
df

        name     place  age
0     Ashwin      Pune   42
1     Sanjay    Satara   20
2      Smita    Sangli   25
3    Vaibhav   Solapur   36
4   Abhijeet  Kolhapur   28
5     Mahesh      Pune   24
6    Supriya    Satara   45
7    Pallavi    Sangli   25
8      Sumit   Solapur   21
9      Chinu      Pune   19
10   Subhash    Satara   45

In [64]:
# i want top 3 entries
df.head(3)

     name   place  age
0  Ashwin    Pune   42
1  Sanjay  Satara   20
2   Smita  Sangli   25

In [65]:
df[:3]

     name   place  age
0  Ashwin    Pune   42
1  Sanjay  Satara   20
2   Smita  Sangli   25

In [70]:
# select random 5 names from series
# Sanjay, Pallavi,Chinu,Smita
df.iloc[[7,9,1,2],:]

      name   place  age
7  Pallavi  Sangli   25
9    Chinu    Pune   19
1   Sanjay  Satara   20
2    Smita  Sangli   25

In [ ]:
# Assignment

In [71]:
# i want last 3 entries
df.tail(3)

       name    place  age
8     Sumit  Solapur   21
9     Chinu     Pune   19
10  Subhash   Satara   45

In [74]:
# I want record of an employee whose age is 42
df[df.age == 42]

     name place  age
0  Ashwin  Pune   42

In [75]:
df.query('age == 42')

     name place  age
0  Ashwin  Pune   42

In [81]:
# i want name of an emp who is from Kolhapur 
r1 = df.query('place == "Kolhapur"')
r1.name

4    Abhijeet
Name: name, dtype: object

In [85]:
# fetch record from Pune region with age < 30
r2 = df.query('place == "Pune"')
r2[r2.age < 30]

     name place  age
5  Mahesh  Pune   24
9   Chinu  Pune   19

In [86]:
#combine 2 conditions 
df.query('place=="Pune" and age < 30')

     name place  age
5  Mahesh  Pune   24
9   Chinu  Pune   19

In [88]:
#Count of Employee per place
#Return a Series containing counts of unique values.
# regionwise count
df.place.value_counts()

Pune        3
Satara      3
Sangli      2
Solapur     2
Kolhapur    1
Name: place, dtype: int64

In [89]:
pl = pd.Series(['Pune','pune','PUNE'])
pl

0    Pune
1    pune
2    PUNE
dtype: object

In [90]:
pl.value_counts()

Pune    1
pune    1
PUNE    1
dtype: int64

In [97]:
#solution for above problem???
pl = pl.str.casefold()
pl.value_counts()

pune    3
dtype: int64

In [99]:
# List the unique cities/places
df.place.unique()

array(['Pune', 'Satara', 'Sangli', 'Solapur', 'Kolhapur'], dtype=object)

In [100]:
# if u want names in alphabatic order then use np
np.unique(df.place)

array(['Kolhapur', 'Pune', 'Sangli', 'Satara', 'Solapur'], dtype=object)

In [102]:
#Count the unique places
#len(df.place.unique())
df.place.nunique()

5

In [ ]:
#fetch records for Place Pune

In [ ]:
#fetch name of emp. whose age is min

In [ ]:
#fetch such records whose name length is>5

In [ ]:
#fetch the record whose name starts with 'M'

In [ ]:
# fetch the name and place whose age is divisible by 4

In [ ]:
#convert places into int ex. Pune=12 Satara=11 likewise

In [ ]:
# I want the records of emp whose age is greater than 30
# I want the emp whose name starts with A
# i want the place of an emp whose name endswith a
# what is age of Akshay
# who is from place Satara
# i want record of emp whose age less than  or equal to 25
# list out the name and age of emp from Sangli location
# add a column with designation 
# find out is there any duplicate entry?
# find out the count of null/NaN values
# what is the age of Akshay?

In [106]:
np.random.random((5,5))

array([[0.844443  , 0.97215462, 0.22898484, 0.95449747, 0.78601181],
       [0.44803694, 0.67328891, 0.8415944 , 0.35055737, 0.85460639],
       [0.45486232, 0.58018961, 0.88766408, 0.94863783, 0.21063244],
       [0.29902608, 0.71971933, 0.63412377, 0.36978795, 0.14004215],
       [0.27259355, 0.63210013, 0.13666709, 0.88498716, 0.72611146]])

In [107]:
np.random.rand(5,5)

array([[0.85101817, 0.91286805, 0.8106708 , 0.08249318, 0.91048421],
       [0.55947915, 0.01313625, 0.70156723, 0.7958018 , 0.69995554],
       [0.93258976, 0.36404012, 0.7529282 , 0.30274116, 0.29059884],
       [0.18142084, 0.52230166, 0.67625555, 0.34728773, 0.09740651],
       [0.4413031 , 0.958442  , 0.80883193, 0.64143117, 0.35747007]])