In [1]:
import numpy as np
import pandas as pd

## query: evaluates expression and returns df

In [2]:
#Query using df

df = pd.DataFrame({'A': range(1, 6),
                   'B': range(10, 0, -2),
                   'C': range(10, 15)})
df

   A   B   C
0  1  10  10
1  2   8  11
2  3   6  12
3  4   4  13
4  5   2  14

In [6]:
#Query the columns of a DataFrame with a boolean expression
df.query('A > B')

   A  B   C
4  5  2  14

In [4]:
df.query('A==3')

   A  B   C
2  3  6  12

In [20]:
# more than one condition
out = df.query('B>4 and A>1')
out[['A','C']]
out.loc[:,['C','A']]
out.iloc[:,[0,2]]

   A   C
1  2  11
2  3  12

In [27]:
#fetch the value from column B where value of column A==3
df.query('A==3').B

2    6
Name: B, dtype: int64

In [26]:
#fetch columb B where A is 3
b1 = df.query('A==3')
b1['B']

2    6
Name: B, dtype: int64

In [30]:
# answer of above question using indexing
df.A == 3

0    False
1    False
2     True
3    False
4    False
Name: A, dtype: bool

In [31]:
df[df.A == 3]

   A  B   C
2  3  6  12

In [42]:
# fetch column A and C where B value is =10
j1 = df[df.B == 10]
j1[['A','C']]

   A   C
0  1  10

In [43]:
df[df.B == 10][['A','C']]

   A   C
0  1  10

In [46]:
#using query
df.query('B == 10')[['A','C']]

   A   C
0  1  10