In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel('batch_19.xlsx')
df.head()

   Sr. No             Name    Place    Post  Salary    Code  Age
0       1    Akshay Bankar      Pune     DS   67000  AK-102   24
1       2      Arati Banne   Solapur     SE   56000  AB-304   20
2       3     Dipak Sawant  Kolhapur  Admin   78000  DS-100   28
3       4    Ganesh Rakate    Sangli     HR   80000  GR-450   63
4       5  Harshala Gondal    Sangli     DS   45000  HG-232   40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sr. No  11 non-null     int64
 1   Name    11 non-null     object
 2   Place   11 non-null     object
 3   Post    11 non-null     object
 4   Salary  11 non-null     int64
 5   Code    11 non-null     object
 6   Age     11 non-null     int64
dtypes: int64(3), object(4)
memory usage: 744.0+ bytes

In [5]:
len(df)

11

In [6]:
df.shape

(11, 7)

In [16]:
df.columns

Index(['Sr. No', 'Name', 'Place ', 'Post', 'Salary', 'Code', 'Age'], dtype='object')

In [20]:
# fetch employees from Sangli location
df[df['Place '] == 'Sangli']

   Sr. No             Name  Place  Post  Salary    Code  Age
3       4    Ganesh Rakate  Sangli   HR   80000  GR-450   63
4       5  Harshala Gondal  Sangli   DS   45000  HG-232   40

In [24]:
# remove space in Place 
df.rename(columns={'Place ':'Place'},inplace=True)

In [25]:
df.columns

Index(['Sr. No', 'Name', 'Place', 'Post', 'Salary', 'Code', 'Age'], dtype='object')

In [29]:
# fetch employees whose name ends with t
df[df.Name.str.endswith('t')]

   Sr. No           Name     Place   Post  Salary    Code  Age
2       3   Dipak Sawant  Kolhapur  Admin   78000  DS-100   28
6       7  Piyush Sawant    Mumbai     SE   89000      PS   59
7       8   Umesh Thorat      Pune     SE   67000  UT-102   28

In [31]:
# fetch employee Name, Place,age whose name ends with t
res = df[df.Name.str.endswith('t')]
res[['Name','Place','Age']]

            Name     Place  Age
2   Dipak Sawant  Kolhapur   28
6  Piyush Sawant    Mumbai   59
7   Umesh Thorat      Pune   28

In [35]:
# Convert Names into Upper case
df.Name = df.Name.str.upper()

In [36]:
df

    Sr. No             Name     Place    Post  Salary    Code  Age
0        1    AKSHAY BANKAR      Pune      DS   67000  AK-102   24
1        2      ARATI BANNE   Solapur      SE   56000  AB-304   20
2        3     DIPAK SAWANT  Kolhapur   Admin   78000  DS-100   28
3        4    GANESH RAKATE    Sangli      HR   80000  GR-450   63
4        5  HARSHALA GONDAL    Sangli      DS   45000  HG-232   40
5        6     KULDIP MULEY      Beed     CEO  120000  KM-333   25
6        7    PIYUSH SAWANT    Mumbai      SE   89000      PS   59
7        8     UMESH THORAT      Pune      SE   67000  UT-102   28
8        9    VAIBHAV LADGE  Kolhapur  Tester   87000  VL-102   22
9       10    SUPRIYA GURAV      Pune      SE   90000  SG-100   35
10      11    SHITAL SHELAR     Karad  Tester   80000  SS-222   33

In [38]:
# get back name column to its original form
df.Name.str.title()

0       Akshay Bankar
1         Arati Banne
2        Dipak Sawant
3       Ganesh Rakate
4     Harshala Gondal
5        Kuldip Muley
6       Piyush Sawant
7        Umesh Thorat
8       Vaibhav Ladge
9       Supriya Gurav
10      Shital Shelar
Name: Name, dtype: object

In [39]:
df.Name = df.Name.str.title()

In [40]:
df

    Sr. No             Name     Place    Post  Salary    Code  Age
0        1    Akshay Bankar      Pune      DS   67000  AK-102   24
1        2      Arati Banne   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav      Pune      SE   90000  SG-100   35
10      11    Shital Shelar     Karad  Tester   80000  SS-222   33

# apply()

In [41]:
df.Name

0       Akshay Bankar
1         Arati Banne
2        Dipak Sawant
3       Ganesh Rakate
4     Harshala Gondal
5        Kuldip Muley
6       Piyush Sawant
7        Umesh Thorat
8       Vaibhav Ladge
9       Supriya Gurav
10      Shital Shelar
Name: Name, dtype: object

In [44]:
df.Name.apply(str.upper)

0       AKSHAY BANKAR
1         ARATI BANNE
2        DIPAK SAWANT
3       GANESH RAKATE
4     HARSHALA GONDAL
5        KULDIP MULEY
6       PIYUSH SAWANT
7        UMESH THORAT
8       VAIBHAV LADGE
9       SUPRIYA GURAV
10      SHITAL SHELAR
Name: Name, dtype: object

In [45]:
#calculate len of each  name
df.Name.apply(len)

0     13
1     11
2     12
3     13
4     15
5     12
6     13
7     12
8     13
9     13
10    13
Name: Name, dtype: int64

In [47]:
df.Code

0     AK-102
1     AB-304
2     DS-100
3     GR-450
4     HG-232
5     KM-333
6         PS
7     UT-102
8     VL-102
9     SG-100
10    SS-222
Name: Code, dtype: object

In [49]:
# From above code column i want seperate ID and Number
# Example: AK-102==> AK     102
df.Code.str.split('-')

0     [AK, 102]
1     [AB, 304]
2     [DS, 100]
3     [GR, 450]
4     [HG, 232]
5     [KM, 333]
6          [PS]
7     [UT, 102]
8     [VL, 102]
9     [SG, 100]
10    [SS, 222]
Name: Code, dtype: object

In [50]:
df.Code.str.split('-',expand=True)

     0     1
0   AK   102
1   AB   304
2   DS   100
3   GR   450
4   HG   232
5   KM   333
6   PS  None
7   UT   102
8   VL   102
9   SG   100
10  SS   222

In [51]:
df.Name

0       Akshay Bankar
1         Arati Banne
2        Dipak Sawant
3       Ganesh Rakate
4     Harshala Gondal
5        Kuldip Muley
6       Piyush Sawant
7        Umesh Thorat
8       Vaibhav Ladge
9       Supriya Gurav
10      Shital Shelar
Name: Name, dtype: object

In [53]:
# Create Fname and Lname column from Name
nm = df.Name.str.split(expand=True)
nm

           0       1
0     Akshay  Bankar
1      Arati   Banne
2      Dipak  Sawant
3     Ganesh  Rakate
4   Harshala  Gondal
5     Kuldip   Muley
6     Piyush  Sawant
7      Umesh  Thorat
8    Vaibhav   Ladge
9    Supriya   Gurav
10    Shital  Shelar

In [57]:
# Add nm into df
pd.concat([df,nm],axis=1)

,Sr. No,Name,Place,Post,Salary,Code,Age,0,1
0,1,Akshay Bankar,Pune,DS,67000,AK-102,24,Akshay,Bankar
1,2,Arati Banne,Solapur,SE,56000,AB-304,20,Arati,Banne
2,3,Dipak Sawant,Kolhapur,Admin,78000,DS-100,28,Dipak,Sawant
3,4,Ganesh Rakate,Sangli,HR,80000,GR-450,63,Ganesh,Rakate
4,5,Harshala Gondal,Sangli,DS,45000,HG-232,40,Harshala,Gondal
5,6,Kuldip Muley,Beed,CEO,120000,KM-333,25,Kuldip,Muley
6,7,Piyush Sawant,Mumbai,SE,89000,PS,59,Piyush,Sawant
7,8,Umesh Thorat,Pune,SE,67000,UT-102,28,Umesh,Thorat
8,9,Vaibhav Ladge,Kolhapur,Tester,87000,VL-102,22,Vaibhav,Ladge
9,10,Supriya Gurav,Pune,SE,90000,SG-100,35,Supriya,Gurav
10,11,Shital Shelar,Karad,Tester,80000,SS-222,33,Shital,Shelar

In [61]:
df.insert(2,column='fname',value=nm[0])

In [62]:
df

    Sr. No             Name     fname     Place    Post  Salary    Code  Age
0        1    Akshay Bankar    Akshay      Pune      DS   67000  AK-102   24
1        2      Arati Banne     Arati   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant     Dipak  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Ganesh    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal  Harshala    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley    Kuldip      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Piyush    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat     Umesh      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge   Vaibhav  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav   Supriya      Pune      SE   90000  SG-100   35
10      11    Shital Shelar    Shital     Karad  Tester   80000  SS-222   33

In [65]:
pd.concat([df[['Name','Age']],nm],axis=1)

               Name  Age         0       1
0     Akshay Bankar   24    Akshay  Bankar
1       Arati Banne   20     Arati   Banne
2      Dipak Sawant   28     Dipak  Sawant
3     Ganesh Rakate   63    Ganesh  Rakate
4   Harshala Gondal   40  Harshala  Gondal
5      Kuldip Muley   25    Kuldip   Muley
6     Piyush Sawant   59    Piyush  Sawant
7      Umesh Thorat   28     Umesh  Thorat
8     Vaibhav Ladge   22   Vaibhav   Ladge
9     Supriya Gurav   35   Supriya   Gurav
10    Shital Shelar   33    Shital  Shelar

In [72]:
nm

           0       1
0     Akshay  Bankar
1      Arati   Banne
2      Dipak  Sawant
3     Ganesh  Rakate
4   Harshala  Gondal
5     Kuldip   Muley
6     Piyush  Sawant
7      Umesh  Thorat
8    Vaibhav   Ladge
9    Supriya   Gurav
10    Shital  Shelar

In [74]:
# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", 
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
df1

     fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

In [75]:
# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
df2

    fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

In [76]:
pd.merge(df1, df2, on = "fruit", how = "inner")

    fruit  market_price  wholesaler_price
0   apple            21                65
1  banana            14                68
2   grape            38                71

In [77]:
df

    Sr. No             Name     fname     Place    Post  Salary    Code  Age
0        1    Akshay Bankar    Akshay      Pune      DS   67000  AK-102   24
1        2      Arati Banne     Arati   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant     Dipak  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Ganesh    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal  Harshala    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley    Kuldip      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Piyush    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat     Umesh      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge   Vaibhav  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav   Supriya      Pune      SE   90000  SG-100   35
10      11    Shital Shelar    Shital     Karad  Tester   80000  SS-222   33

In [79]:
# Postwise count
df.Post.value_counts()

SE        4
DS        2
Tester    2
Admin     1
HR        1
CEO       1
Name: Post, dtype: int64

In [83]:
df.groupby('Post').count().Name

Post
Admin     1
CEO       1
DS        2
HR        1
SE        4
Tester    2
Name: Name, dtype: int64

In [86]:
# Find out record of an employee whose salary is max
# find max salary 
m_sal = df.Salary.max()
m_sal

120000

In [94]:
df[df.Salary == m_sal]

   Sr. No          Name   fname Place Post  Salary    Code  Age
5       6  Kuldip Muley  Kuldip  Beed  CEO  120000  KM-333   25

In [98]:
# fetch employees from Pune with salary >80k
df.query('Place == "Pune" and Salary > 80000')

   Sr. No           Name    fname Place Post  Salary    Code  Age
9      10  Supriya Gurav  Supriya  Pune   SE   90000  SG-100   35

In [99]:
df

    Sr. No             Name     fname     Place    Post  Salary    Code  Age
0        1    Akshay Bankar    Akshay      Pune      DS   67000  AK-102   24
1        2      Arati Banne     Arati   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant     Dipak  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Ganesh    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal  Harshala    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley    Kuldip      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Piyush    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat     Umesh      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge   Vaibhav  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav   Supriya      Pune      SE   90000  SG-100   35
10      11    Shital Shelar    Shital     Karad  Tester   80000  SS-222   33

In [104]:
# WHat is an Average salary of SE
se = df.query('Post == "SE"')
se.Salary.mean()

75500.0

In [107]:
df.sample(3)

   Sr. No           Name   fname    Place Post  Salary    Code  Age
7       8   Umesh Thorat   Umesh     Pune   SE   67000  UT-102   28
1       2    Arati Banne   Arati  Solapur   SE   56000  AB-304   20
6       7  Piyush Sawant  Piyush   Mumbai   SE   89000      PS   59

In [108]:
del df.sample(3)

SyntaxError: cannot delete function call (Temp/ipykernel_9488/2035085890.py, line 1)

In [109]:
random  =  df.sample(3)
random

    Sr. No           Name   fname   Place    Post  Salary    Code  Age
6        7  Piyush Sawant  Piyush  Mumbai      SE   89000      PS   59
10      11  Shital Shelar  Shital   Karad  Tester   80000  SS-222   33
0        1  Akshay Bankar  Akshay    Pune      DS   67000  AK-102   24

In [111]:
random.index

Int64Index([6, 10, 0], dtype='int64')

In [112]:
df.drop(index=random.index)

   Sr. No             Name     fname     Place    Post  Salary    Code  Age
1       2      Arati Banne     Arati   Solapur      SE   56000  AB-304   20
2       3     Dipak Sawant     Dipak  Kolhapur   Admin   78000  DS-100   28
3       4    Ganesh Rakate    Ganesh    Sangli      HR   80000  GR-450   63
4       5  Harshala Gondal  Harshala    Sangli      DS   45000  HG-232   40
5       6     Kuldip Muley    Kuldip      Beed     CEO  120000  KM-333   25
7       8     Umesh Thorat     Umesh      Pune      SE   67000  UT-102   28
8       9    Vaibhav Ladge   Vaibhav  Kolhapur  Tester   87000  VL-102   22
9      10    Supriya Gurav   Supriya      Pune      SE   90000  SG-100   35