In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel('batch_19.xlsx')
df.head(2)

   Sr. No           Name   Place  Post  Salary    Code  Age
0       1  Akshay Bankar     Pune   DS   67000  AK-102   24
1       2    Arati Banne  Solapur   SE   56000  AB-304   20

In [4]:
#Fetch a record on DS using a groupby
df.groupby('Post').get_group('DS')

   Sr. No             Name  Place  Post  Salary    Code  Age
0       1    Akshay Bankar    Pune   DS   67000  AK-102   24
4       5  Harshala Gondal  Sangli   DS   45000  HG-232   40

In [5]:
#without groupby
df.query('Post == "DS"')

   Sr. No             Name  Place  Post  Salary    Code  Age
0       1    Akshay Bankar    Pune   DS   67000  AK-102   24
4       5  Harshala Gondal  Sangli   DS   45000  HG-232   40

In [8]:
# Sort the data wrt Age
df.sort_values(by='Age')

    Sr. No             Name    Place     Post  Salary    Code  Age
1        2      Arati Banne   Solapur      SE   56000  AB-304   20
8        9    Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
0        1    Akshay Bankar      Pune      DS   67000  AK-102   24
5        6     Kuldip Muley      Beed     CEO  120000  KM-333   25
2        3     Dipak Sawant  Kolhapur   Admin   78000  DS-100   28
7        8     Umesh Thorat      Pune      SE   67000  UT-102   28
10      11    Shital Shelar     Karad  Tester   80000  SS-222   33
9       10    Supriya Gurav      Pune      SE   90000  SG-100   35
4        5  Harshala Gondal    Sangli      DS   45000  HG-232   40
6        7    Piyush Sawant    Mumbai      SE   89000      PS   59
3        4    Ganesh Rakate    Sangli      HR   80000  GR-450   63

In [10]:
df.Age.sort_values()

1     20
8     22
0     24
5     25
2     28
7     28
10    33
9     35
4     40
6     59
3     63
Name: Age, dtype: int64

In [18]:
# Fetch Post and Salary of an employee from Solapur
ans = df.groupby('Place ').get_group('Solapur')
ans[['Post','Salary']]

  Post  Salary
1   SE   56000

In [22]:
ans2 = df[df['Place '] == 'Solapur']
ans2[['Post','Salary']]

  Post  Salary
1   SE   56000

In [23]:
df

    Sr. No             Name    Place     Post  Salary    Code  Age
0        1    Akshay Bankar      Pune      DS   67000  AK-102   24
1        2      Arati Banne   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav      Pune      SE   90000  SG-100   35
10      11    Shital Shelar     Karad  Tester   80000  SS-222   33

In [27]:
df[df.Post.str.startswith('DS')]

   Sr. No             Name  Place  Post  Salary    Code  Age
0       1    Akshay Bankar    Pune   DS   67000  AK-102   24
4       5  Harshala Gondal  Sangli   DS   45000  HG-232   40

In [29]:
# FEtch Umesh record using query
df.query('Name == "Umesh Thorat"')

   Sr. No          Name Place  Post  Salary    Code  Age
7       8  Umesh Thorat   Pune   SE   67000  UT-102   28

In [31]:
# Fetch Min and Max salary for each Post with employee details
df.groupby('Post').agg([min,max])

       Sr. No               Name                     Place             Salary  \
          min max            min              max       min       max     min
Post
Admin       3   3   Dipak Sawant     Dipak Sawant  Kolhapur  Kolhapur   78000
CEO         6   6   Kuldip Muley     Kuldip Muley      Beed      Beed  120000
DS          1   5  Akshay Bankar  Harshala Gondal      Pune    Sangli   45000
HR          4   4  Ganesh Rakate    Ganesh Rakate    Sangli    Sangli   80000
SE          2  10    Arati Banne     Umesh Thorat    Mumbai   Solapur   56000
Tester      9  11  Shital Shelar    Vaibhav Ladge     Karad  Kolhapur   80000

                  Code         Age
           max     min     max min max
Post
Admin    78000  DS-100  DS-100  28  28
CEO     120000  KM-333  KM-333  25  25
DS       67000  AK-102  HG-232  24  40
HR       80000  GR-450  GR-450  63  63
SE       90000  AB-304  UT-102  20  59
Tester   87000  SS-222  VL-102  22  33

In [36]:
# Fetching random 3 rows
random= df.sample(3)
random

    Sr. No           Name    Place     Post  Salary    Code  Age
8        9  Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
1        2    Arati Banne   Solapur      SE   56000  AB-304   20
10      11  Shital Shelar     Karad  Tester   80000  SS-222   33

In [37]:
random.index

Int64Index([8, 1, 10], dtype='int64')

In [38]:
# delete random rows
df.drop(index=random.index)

   Sr. No             Name    Place    Post  Salary    Code  Age
0       1    Akshay Bankar      Pune     DS   67000  AK-102   24
2       3     Dipak Sawant  Kolhapur  Admin   78000  DS-100   28
3       4    Ganesh Rakate    Sangli     HR   80000  GR-450   63
4       5  Harshala Gondal    Sangli     DS   45000  HG-232   40
5       6     Kuldip Muley      Beed    CEO  120000  KM-333   25
6       7    Piyush Sawant    Mumbai     SE   89000      PS   59
7       8     Umesh Thorat      Pune     SE   67000  UT-102   28
9      10    Supriya Gurav      Pune     SE   90000  SG-100   35

In [44]:
# reverse rows and columns
#df[::-1] #reverse the rows
df.loc[::-1,::-1]

    Age    Code  Salary    Post    Place              Name  Sr. No
10   33  SS-222   80000  Tester     Karad    Shital Shelar      11
9    35  SG-100   90000      SE      Pune    Supriya Gurav      10
8    22  VL-102   87000  Tester  Kolhapur    Vaibhav Ladge       9
7    28  UT-102   67000      SE      Pune     Umesh Thorat       8
6    59      PS   89000      SE    Mumbai    Piyush Sawant       7
5    25  KM-333  120000     CEO      Beed     Kuldip Muley       6
4    40  HG-232   45000      DS    Sangli  Harshala Gondal       5
3    63  GR-450   80000      HR    Sangli    Ganesh Rakate       4
2    28  DS-100   78000   Admin  Kolhapur     Dipak Sawant       3
1    20  AB-304   56000      SE   Solapur      Arati Banne       2
0    24  AK-102   67000      DS      Pune    Akshay Bankar       1

In [47]:
# fetch record below avg salary
mn = df.Salary.mean()
mn

78090.90909090909

In [51]:
df[df.Salary < mn]

   Sr. No             Name    Place    Post  Salary    Code  Age
0       1    Akshay Bankar      Pune     DS   67000  AK-102   24
1       2      Arati Banne   Solapur     SE   56000  AB-304   20
2       3     Dipak Sawant  Kolhapur  Admin   78000  DS-100   28
4       5  Harshala Gondal    Sangli     DS   45000  HG-232   40
7       8     Umesh Thorat      Pune     SE   67000  UT-102   28

In [53]:
# Add a row with Name, Age , Salary
d = {'Name':'Maulaali','Age':32,'Salary':67000}
d

{'Name': 'Maulaali', 'Age': 32, 'Salary': 67000}

In [55]:
df.append(d,ignore_index=True)

    Sr. No             Name    Place     Post  Salary    Code  Age
0      1.0    Akshay Bankar      Pune      DS   67000  AK-102   24
1      2.0      Arati Banne   Solapur      SE   56000  AB-304   20
2      3.0     Dipak Sawant  Kolhapur   Admin   78000  DS-100   28
3      4.0    Ganesh Rakate    Sangli      HR   80000  GR-450   63
4      5.0  Harshala Gondal    Sangli      DS   45000  HG-232   40
5      6.0     Kuldip Muley      Beed     CEO  120000  KM-333   25
6      7.0    Piyush Sawant    Mumbai      SE   89000      PS   59
7      8.0     Umesh Thorat      Pune      SE   67000  UT-102   28
8      9.0    Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
9     10.0    Supriya Gurav      Pune      SE   90000  SG-100   35
10    11.0    Shital Shelar     Karad  Tester   80000  SS-222   33
11     NaN         Maulaali       NaN     NaN   67000     NaN   32

In [56]:
df

    Sr. No             Name    Place     Post  Salary    Code  Age
0        1    Akshay Bankar      Pune      DS   67000  AK-102   24
1        2      Arati Banne   Solapur      SE   56000  AB-304   20
2        3     Dipak Sawant  Kolhapur   Admin   78000  DS-100   28
3        4    Ganesh Rakate    Sangli      HR   80000  GR-450   63
4        5  Harshala Gondal    Sangli      DS   45000  HG-232   40
5        6     Kuldip Muley      Beed     CEO  120000  KM-333   25
6        7    Piyush Sawant    Mumbai      SE   89000      PS   59
7        8     Umesh Thorat      Pune      SE   67000  UT-102   28
8        9    Vaibhav Ladge  Kolhapur  Tester   87000  VL-102   22
9       10    Supriya Gurav      Pune      SE   90000  SG-100   35
10      11    Shital Shelar     Karad  Tester   80000  SS-222   33

In [62]:
df.values

array([[1, 'Akshay Bankar', 'Pune', 'DS', 67000, 'AK-102', 24],
       [2, 'Arati Banne', 'Solapur', 'SE', 56000, 'AB-304', 20],
       [3, 'Dipak Sawant', 'Kolhapur', 'Admin', 78000, 'DS-100', 28],
       [4, 'Ganesh Rakate', 'Sangli', 'HR', 80000, 'GR-450', 63],
       [5, 'Harshala Gondal', 'Sangli', 'DS', 45000, 'HG-232', 40],
       [6, 'Kuldip Muley', 'Beed', 'CEO', 120000, 'KM-333', 25],
       [7, 'Piyush Sawant', 'Mumbai', 'SE', 89000, 'PS', 59],
       [8, 'Umesh Thorat', 'Pune', 'SE', 67000, 'UT-102', 28],
       [9, 'Vaibhav Ladge', 'Kolhapur', 'Tester', 87000, 'VL-102', 22],
       [10, 'Supriya Gurav', 'Pune', 'SE', 90000, 'SG-100', 35],
       [11, 'Shital Shelar', 'Karad', 'Tester', 80000, 'SS-222', 33]],
      dtype=object)

In [61]:
pd.DataFrame(np.insert(df.values,4,[101,'Jones','Dubai','Tester',90000,'UAE-100',34],axis = 0), columns = df.columns)

   Sr. No             Name    Place     Post  Salary     Code Age
0       1    Akshay Bankar      Pune      DS   67000   AK-102  24
1       2      Arati Banne   Solapur      SE   56000   AB-304  20
2       3     Dipak Sawant  Kolhapur   Admin   78000   DS-100  28
3       4    Ganesh Rakate    Sangli      HR   80000   GR-450  63
4     101            Jones     Dubai  Tester   90000  UAE-100  34
5       5  Harshala Gondal    Sangli      DS   45000   HG-232  40
6       6     Kuldip Muley      Beed     CEO  120000   KM-333  25
7       7    Piyush Sawant    Mumbai      SE   89000       PS  59
8       8     Umesh Thorat      Pune      SE   67000   UT-102  28
9       9    Vaibhav Ladge  Kolhapur  Tester   87000   VL-102  22
10     10    Supriya Gurav      Pune      SE   90000   SG-100  35
11     11    Shital Shelar     Karad  Tester   80000   SS-222  33

In [66]:
e = pd.DataFrame()
e.__sizeof__()

0

In [67]:
d = pd.DataFrame(np.random.random((4,5)))
d

          0         1         2         3         4
0  0.277465  0.779753  0.297460  0.059841  0.167167
1  0.089723  0.859918  0.337614  0.554055  0.582489
2  0.419609  0.932432  0.498847  0.664213  0.798321
3  0.965610  0.171600  0.445822  0.947058  0.513537

In [68]:
d.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [69]:
type(d)

pandas.core.frame.DataFrame

In [70]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [71]:
# Remove duplicate rows
f = pd.DataFrame([[1,2],[1,2],[3,4]])
f

   0  1
0  1  2
1  1  2
2  3  4

In [73]:
f[f.duplicated()]

   0  1
1  1  2

In [76]:
f.drop_duplicates(ignore_index=True)

   0  1
0  1  2
1  3  4

In [101]:
# Remove duplicate columns
h = pd.DataFrame([[1,1],[1,1]],columns=['A','A'])
h

   A  A
0  1  1
1  1  1

In [85]:
# transpose
h.T

   0  1
A  1  1
A  1  1

In [86]:
h.T.duplicated()

A    False
A     True
dtype: bool

In [87]:
h.T.drop_duplicates()

   0  1
A  1  1

In [88]:
# Drop duplicate column names

In [89]:
h

   A  A
0  1  1
1  1  1

In [90]:
np.unique(h.columns)

array(['A'], dtype=object)

In [94]:
h['A']

   A  A
0  1  1
1  1  1

In [102]:
ls = list(h.columns)
ls

['A', 'A']

In [97]:
for i in h:
    if i in ls:
        print(h[i])

   A  A
0  1  1
1  1  1
   A  A
0  1  1
1  1  1

In [98]:
h.pop('A')

   A  A
0  1  1
1  1  1

In [99]:
h

Empty DataFrame
Columns: []
Index: [0, 1]

In [103]:
h

   A  A
0  1  1
1  1  1

In [104]:
# This function take a dataframe 
# as a parameter and returning list 
# of column names whose contents  
# are duplicates. 
def getDuplicateColumns(df): 
  
    # Create an empty set 
    duplicateColumnNames = set() 
      
    # Iterate through all the columns  
    # of dataframe 
    for x in range(df.shape[1]): 
          
        # Take column at xth index. 
        col = df.iloc[:, x] 
          
        # Iterate through all the columns in 
        # DataFrame from (x + 1)th index to 
        # last index 
        for y in range(x + 1, df.shape[1]): 
              
            # Take column at yth index. 
            otherCol = df.iloc[:, y] 
              
            # Check if two columns at x & y 
            # index are equal or not, 
            # if equal then adding  
            # to the set 
            if col.equals(otherCol): 
                duplicateColumnNames.add(df.columns.values[y]) 
                  
    # Return list of unique column names  
    # whose contents are duplicates. 
    return list(duplicateColumnNames) 
  
# Driver code 
if __name__ == "__main__" : 
  
    
  
    # Create a DataFrame object 
    df = h 
  
  
    # Get list of duplicate columns 
    duplicateColNames = getDuplicateColumns(df) 
  
    print('Duplicate Columns are :') 
        
    # Iterate through duplicate 
    # column names 
    for column in duplicateColNames : 
       print('Column Name : ', column)

Duplicate Columns are :
Column Name :  A

In [106]:
df

   A  A
0  1  1
1  1  1

In [107]:
df.loc[:, ~df.columns.duplicated()]

   A
0  1
1  1