In [1]:
import pandas as pd

In [31]:
d = {'Name':['Harsh','Megha','Pratik','Pravin','Tejas','Vrunda'],
    'Gender':['M','F','M','M','M','F'],
    'Post':['DS','SE','Dev','DS','Tester','SE'],
    'Age':[19,34,56,17,25,37],
    'Salary':[36000,45000,55000,120000,67000,180000]}
d

{'Name': ['Harsh', 'Megha', 'Pratik', 'Pravin', 'Tejas', 'Vrunda'],
 'Gender': ['M', 'F', 'M', 'M', 'M', 'F'],
 'Post': ['DS', 'SE', 'Dev', 'DS', 'Tester', 'SE'],
 'Age': [19, 34, 56, 17, 25, 37],
 'Salary': [36000, 45000, 55000, 120000, 67000, 180000]}

In [32]:
df = pd.DataFrame(d)
df

     Name Gender    Post  Age  Salary
0   Harsh      M      DS   19   36000
1   Megha      F      SE   34   45000
2  Pratik      M     Dev   56   55000
3  Pravin      M      DS   17  120000
4   Tejas      M  Tester   25   67000
5  Vrunda      F      SE   37  180000

## Check total records

In [6]:
df.shape

(6, 5)

## Dimension

In [7]:
df.ndim

2

## Data types of all columns

In [8]:
df.dtypes

Name      object
Gender    object
Post      object
Age        int64
Salary     int64
dtype: object

## List the column names

In [9]:
df.columns

Index(['Name', 'Gender', 'Post', 'Age', 'Salary'], dtype='object')

### How to Access columns

In [15]:
#access single column
df.Salary

0     36000
1     45000
2     55000
3    120000
4     67000
5    180000
Name: Salary, dtype: int64

In [22]:
df.Gender

0    M
1    F
2    M
3    M
4    M
5    F
Name: Gender, dtype: object

In [19]:
df.columns

Index(['Name', 'Gender', 'Post', 'Age', 'Salary'], dtype='object')

In [24]:
#another option to access a single column
df['Post']

0        DS
1        SE
2       Dev
3        DS
4    Tester
5        SE
Name: Post, dtype: object

In [42]:
df.Gender.values.itemsize

8

In [62]:
df.Gender.size

6

In [45]:
#acess more columns
df[['Gender']].ndim

2

In [46]:
df['Gender'].ndim

1

In [47]:
df[['Name','Gender']]

     Name Gender
0   Harsh      M
1   Megha      F
2  Pratik      M
3  Pravin      M
4   Tejas      M
5  Vrunda      F

In [50]:
#while selecting sequence doesnt matter
df[['Gender','Salary','Name']]

  Gender  Salary    Name
0      M   36000   Harsh
1      F   45000   Megha
2      M   55000  Pratik
3      M  120000  Pravin
4      M   67000   Tejas
5      F  180000  Vrunda

## Selection can be performed using 2 other options
- loc
- iloc

## loc: label based selection

In [52]:
#df.loc[]# it will first work on rows
df.loc[3:]

     Name Gender    Post  Age  Salary
3  Pravin      M      DS   17  120000
4   Tejas      M  Tester   25   67000
5  Vrunda      F      SE   37  180000

In [53]:
df.loc[::-1] #reverse rows

     Name Gender    Post  Age  Salary
5  Vrunda      F      SE   37  180000
4   Tejas      M  Tester   25   67000
3  Pravin      M      DS   17  120000
2  Pratik      M     Dev   56   55000
1   Megha      F      SE   34   45000
0   Harsh      M      DS   19   36000

In [54]:
#other option in loc
df.loc[:,:] 
# [rows,columns]

     Name Gender    Post  Age  Salary
0   Harsh      M      DS   19   36000
1   Megha      F      SE   34   45000
2  Pratik      M     Dev   56   55000
3  Pravin      M      DS   17  120000
4   Tejas      M  Tester   25   67000
5  Vrunda      F      SE   37  180000

In [55]:
df.loc[:,'Name':'Post']
# stop is inclusive

     Name Gender    Post
0   Harsh      M      DS
1   Megha      F      SE
2  Pratik      M     Dev
3  Pravin      M      DS
4   Tejas      M  Tester
5  Vrunda      F      SE

In [57]:
df.loc[:,'Gender'::2]

  Gender  Age
0      M   19
1      F   34
2      M   56
3      M   17
4      M   25
5      F   37

In [61]:
#access name ,post , salary
df.loc[:,::2]

     Name    Post  Salary
0   Harsh      DS   36000
1   Megha      SE   45000
2  Pratik     Dev   55000
3  Pravin      DS  120000
4   Tejas  Tester   67000
5  Vrunda      SE  180000

### Lets work on rows

In [65]:
df.loc[::2,'Name':'Age']

     Name Gender    Post  Age
0   Harsh      M      DS   19
2  Pratik      M     Dev   56
4   Tejas      M  Tester   25

In [68]:
#harsh,megha,Vrunda,pravin
df.loc[[0,1,5,3],:]

     Name Gender Post  Age  Salary
0   Harsh      M   DS   19   36000
1   Megha      F   SE   34   45000
5  Vrunda      F   SE   37  180000
3  Pravin      M   DS   17  120000

In [70]:
# Name,Salary, Post
df.loc[:,['Name','Salary','Post']]

     Name  Salary    Post
0   Harsh   36000      DS
1   Megha   45000      SE
2  Pratik   55000     Dev
3  Pravin  120000      DS
4   Tejas   67000  Tester
5  Vrunda  180000      SE

## iloc: integer/index based selection

In [72]:
df.iloc[:,:]

     Name Gender    Post  Age  Salary
0   Harsh      M      DS   19   36000
1   Megha      F      SE   34   45000
2  Pratik      M     Dev   56   55000
3  Pravin      M      DS   17  120000
4   Tejas      M  Tester   25   67000
5  Vrunda      F      SE   37  180000

In [76]:
df.iloc[1:3,:]
# stop is exclusive in iloc

     Name Gender Post  Age  Salary
1   Megha      F   SE   34   45000
2  Pratik      M  Dev   56   55000

In [81]:
#work on columns
df.iloc[:,:2]

     Name Gender
0   Harsh      M
1   Megha      F
2  Pratik      M
3  Pravin      M
4   Tejas      M
5  Vrunda      F

In [83]:
# column: Post , Name, Age
# row: Tejas,Megha,Harsh
df.iloc[[4,1,0],[2,0,3]]

     Post   Name  Age
4  Tester  Tejas   25
1      SE  Megha   34
0      DS  Harsh   19

In [89]:
# Access rows present at odd index
df.iloc[1::2]

     Name Gender Post  Age  Salary
1   Megha      F   SE   34   45000
3  Pravin      M   DS   17  120000
5  Vrunda      F   SE   37  180000

In [91]:
df[1::2]

     Name Gender Post  Age  Salary
1   Megha      F   SE   34   45000
3  Pravin      M   DS   17  120000
5  Vrunda      F   SE   37  180000

### Indexing over dataframe works on Columns
### Slcing over dataframe works on Rows

In [101]:
df['Name']

0     Harsh
1     Megha
2    Pratik
3    Pravin
4     Tejas
5    Vrunda
Name: Name, dtype: object

In [95]:
df[::-1]

     Name Gender    Post  Age  Salary
5  Vrunda      F      SE   37  180000
4   Tejas      M  Tester   25   67000
3  Pravin      M      DS   17  120000
2  Pratik      M     Dev   56   55000
1   Megha      F      SE   34   45000
0   Harsh      M      DS   19   36000

## How to conver Series and DataFrame into an array

In [103]:
s1 = df.Name
s1

0     Harsh
1     Megha
2    Pratik
3    Pravin
4     Tejas
5    Vrunda
Name: Name, dtype: object

In [110]:
#convert s1 into numpy array
s1.values

array(['Harsh', 'Megha', 'Pratik', 'Pravin', 'Tejas', 'Vrunda'],
      dtype=object)

In [107]:
df

     Name Gender    Post  Age  Salary
0   Harsh      M      DS   19   36000
1   Megha      F      SE   34   45000
2  Pratik      M     Dev   56   55000
3  Pravin      M      DS   17  120000
4   Tejas      M  Tester   25   67000
5  Vrunda      F      SE   37  180000

In [112]:
df.values

array([['Harsh', 'M', 'DS', 19, 36000],
       ['Megha', 'F', 'SE', 34, 45000],
       ['Pratik', 'M', 'Dev', 56, 55000],
       ['Pravin', 'M', 'DS', 17, 120000],
       ['Tejas', 'M', 'Tester', 25, 67000],
       ['Vrunda', 'F', 'SE', 37, 180000]], dtype=object)

In [113]:
import numpy as np

In [114]:
np.array(df.Name)

array(['Harsh', 'Megha', 'Pratik', 'Pravin', 'Tejas', 'Vrunda'],
      dtype=object)

In [115]:
np.array(df)

array([['Harsh', 'M', 'DS', 19, 36000],
       ['Megha', 'F', 'SE', 34, 45000],
       ['Pratik', 'M', 'Dev', 56, 55000],
       ['Pravin', 'M', 'DS', 17, 120000],
       ['Tejas', 'M', 'Tester', 25, 67000],
       ['Vrunda', 'F', 'SE', 37, 180000]], dtype=object)

In [116]:
df.to_numpy()

array([['Harsh', 'M', 'DS', 19, 36000],
       ['Megha', 'F', 'SE', 34, 45000],
       ['Pratik', 'M', 'Dev', 56, 55000],
       ['Pravin', 'M', 'DS', 17, 120000],
       ['Tejas', 'M', 'Tester', 25, 67000],
       ['Vrunda', 'F', 'SE', 37, 180000]], dtype=object)