In [1]:
import numpy as np
import pandas as pd

In [3]:
data = np.random.random((4,3))
data

array([[0.27558068, 0.9318565 , 0.91062627],
       [0.11993094, 0.29235358, 0.64235027],
       [0.72069289, 0.70964287, 0.2864859 ],
       [0.88812746, 0.39954856, 0.85926444]])

In [9]:
d = pd.DataFrame(data,columns=['dt_1','dt_2','dt_3'])
d

       dt_1      dt_2      dt_3
0  0.275581  0.931856  0.910626
1  0.119931  0.292354  0.642350
2  0.720693  0.709643  0.286486
3  0.888127  0.399549  0.859264

In [10]:
#check column names
d.columns

Index(['dt_1', 'dt_2', 'dt_3'], dtype='object')

In [11]:
#Q. change all column names/replace column names with new one
d.columns = ['Bhagwan','Krupa','Suraj']

In [12]:
d

    Bhagwan     Krupa     Suraj
0  0.275581  0.931856  0.910626
1  0.119931  0.292354  0.642350
2  0.720693  0.709643  0.286486
3  0.888127  0.399549  0.859264

In [14]:
# Q. replace a name of single column
d.rename(columns={'Suraj':'Rakesh'})
#will give temp output

    Bhagwan     Krupa    Rakesh
0  0.275581  0.931856  0.910626
1  0.119931  0.292354  0.642350
2  0.720693  0.709643  0.286486
3  0.888127  0.399549  0.859264

In [16]:
# but if i want permanent change
d.rename(columns={'Suraj':'Rakesh'},inplace=True)

In [17]:
d

    Bhagwan     Krupa    Rakesh
0  0.275581  0.931856  0.910626
1  0.119931  0.292354  0.642350
2  0.720693  0.709643  0.286486
3  0.888127  0.399549  0.859264

In [21]:
d.rename(index={1:101})

      Bhagwan     Krupa    Rakesh
0    0.275581  0.931856  0.910626
101  0.119931  0.292354  0.642350
2    0.720693  0.709643  0.286486
3    0.888127  0.399549  0.859264

In [22]:
d.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
#using above option its also possible to change index
d.index = ['A','B','C','D']
#its inplace

In [25]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [31]:
d2 = d[:2].index = ['X','Y']
d2

['X', 'Y']

In [30]:
d[:2342]

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [32]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [34]:
d[:2].index

Index(['A', 'B'], dtype='object')

In [36]:
dict(zip(d[:2].index,['X','Y']))

{'A': 'X', 'B': 'Y'}

In [38]:
d.rename(index=dict(zip(d[:2].index,['X','Y'])))

    Bhagwan     Krupa    Rakesh
X  0.275581  0.931856  0.910626
Y  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [39]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

## check different properties of Dataframe

In [40]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [41]:
# check number of rows and columns
d.shape

(4, 3)

In [42]:
# check total element
d.size

12

In [43]:
# check data type
d.dtypes

Bhagwan    float64
Krupa      float64
Rakesh     float64
dtype: object

In [45]:
# check descriptive summary of data
# Print a concise summary of a DataFrame.
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Bhagwan  4 non-null      float64
 1   Krupa    4 non-null      float64
 2   Rakesh   4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes

In [46]:
# descriptive statistics
d.describe()

        Bhagwan     Krupa    Rakesh
count  4.000000  4.000000  4.000000
mean   0.501083  0.583350  0.674682
std    0.362473  0.292044  0.283715
min    0.119931  0.292354  0.286486
25%    0.236668  0.372750  0.553384
50%    0.498137  0.554596  0.750807
75%    0.762552  0.765196  0.872105
max    0.888127  0.931856  0.910626

In [47]:
# transpose
d.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Bhagwan,4.0,0.501083,0.362473,0.119931,0.236668,0.498137,0.762552,0.888127
Krupa,4.0,0.583350,0.292044,0.292354,0.372750,0.554596,0.765196,0.931856
Rakesh,4.0,0.674682,0.283715,0.286486,0.553384,0.750807,0.872105,0.910626

In [48]:
# i want answer of each factor separtely
# conside Rakesh column
d.Rakesh

A    0.910626
B    0.642350
C    0.286486
D    0.859264
Name: Rakesh, dtype: float64

### count

In [49]:
d.Rakesh.count()

4

In [50]:
len(d.Rakesh)

4

In [52]:
type(d.Rakesh)

pandas.core.series.Series

In [54]:
d.Rakesh.size

4

### mean()

In [55]:
d.Rakesh.mean()

0.6746817211344592

In [57]:
# i want mean of all columns
d.mean()
#columnwise

Bhagwan    0.501083
Krupa      0.583350
Rakesh     0.674682
dtype: float64

In [60]:
# rowise mean
d.mean(axis=1)

A    0.706021
B    0.351545
C    0.572274
D    0.715647
dtype: float64

In [62]:
(0.275581 + 0.931856 + 0.910626)/3

0.7060210000000001

In [66]:
# if we apply indexing over df hen it works default on column
d['Krupa']

A    0.931856
B    0.292354
C    0.709643
D    0.399549
Name: Krupa, dtype: float64

In [68]:
f = np.random.random((3,3))
f

array([[0.36464169, 0.2245005 , 0.01845414],
       [0.11210138, 0.49570781, 0.43978687],
       [0.89472657, 0.92364869, 0.27575709]])

In [69]:
f[0]

array([0.36464169, 0.2245005 , 0.01845414])

In [70]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [71]:
s[0]

10

#### Std()

In [73]:
d.Bhagwan

A    0.275581
B    0.119931
C    0.720693
D    0.888127
Name: Bhagwan, dtype: float64

In [74]:
d.Bhagwan.std()

0.3624730352070185

In [75]:
#std of all columns
d.std()

Bhagwan    0.362473
Krupa      0.292044
Rakesh     0.283715
dtype: float64

In [76]:
#rowwise std
d.std(axis=1)

A    0.372923
B    0.266192
C    0.247561
D    0.274129
dtype: float64

Assigment:
apply max,min

In [78]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [79]:
d.ndim

2

In [82]:
d.std()

Bhagwan    0.362473
Krupa      0.292044
Rakesh     0.283715
dtype: float64

In [83]:
d.std().std() #all columns std

0.0432676880161851

In [87]:
d.values.flatten().std() #std of all data

0.28163782752859745

In [88]:
d.values

array([[0.27558068, 0.9318565 , 0.91062627],
       [0.11993094, 0.29235358, 0.64235027],
       [0.72069289, 0.70964287, 0.2864859 ],
       [0.88812746, 0.39954856, 0.85926444]])

In [89]:
d.values.flatten()

array([0.27558068, 0.9318565 , 0.91062627, 0.11993094, 0.29235358,
       0.64235027, 0.72069289, 0.70964287, 0.2864859 , 0.88812746,
       0.39954856, 0.85926444])

In [90]:
d.values.flatten().std()

0.28163782752859745

In [91]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [93]:
d.Bhagwan.mean() #X bar

0.5010829915391024

In [94]:
np.sqrt((0.888127 - d.Bhagwan.mean())/3)

0.3591861209553702

# Selection of columns

In [96]:
d

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [97]:
d.Rakesh

A    0.910626
B    0.642350
C    0.286486
D    0.859264
Name: Rakesh, dtype: float64

In [98]:
d['Rakesh']

A    0.910626
B    0.642350
C    0.286486
D    0.859264
Name: Rakesh, dtype: float64

In [101]:
# 2D df
d[['Rakesh']]

     Rakesh
A  0.910626
B  0.642350
C  0.286486
D  0.859264

In [106]:
#access more than one column
d[['Rakesh','Krupa','Bhagwan']]

     Rakesh     Krupa   Bhagwan
A  0.910626  0.931856  0.275581
B  0.642350  0.292354  0.119931
C  0.286486  0.709643  0.720693
D  0.859264  0.399549  0.888127

## loc: location based selection/label based selection

In [108]:
d.loc[:,:] # [rows,columns]

    Bhagwan     Krupa    Rakesh
A  0.275581  0.931856  0.910626
B  0.119931  0.292354  0.642350
C  0.720693  0.709643  0.286486
D  0.888127  0.399549  0.859264

In [109]:
#work on columns
d.loc[:,'Krupa':]

      Krupa    Rakesh
A  0.931856  0.910626
B  0.292354  0.642350
C  0.709643  0.286486
D  0.399549  0.859264

In [111]:
d.loc[:,'Bhagwan'::2]

    Bhagwan    Rakesh
A  0.275581  0.910626
B  0.119931  0.642350
C  0.720693  0.286486
D  0.888127  0.859264

In [112]:
#reverse column order
d.loc[:,::-1]

     Rakesh     Krupa   Bhagwan
A  0.910626  0.931856  0.275581
B  0.642350  0.292354  0.119931
C  0.286486  0.709643  0.720693
D  0.859264  0.399549  0.888127

In [113]:
d.loc[:,['Krupa','Bhagwan','Rakesh']]

      Krupa   Bhagwan    Rakesh
A  0.931856  0.275581  0.910626
B  0.292354  0.119931  0.642350
C  0.709643  0.720693  0.286486
D  0.399549  0.888127  0.859264

## Assignment apply different options over rows using loc