# DataFrame

# 2D data structure
# composed of rows and columns
# We can create multiple rows and multiple columns with different data types
# powerful option for data science and analysis
# it contains so many options for selection, filteration, merging, deletion..
# Dataframe is a combination of multiple series

In [1]:
import pandas as pd

In [2]:
# Create Empty dataFrame
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [3]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Structure of Dataframe
pd.DataFrame()
"""
(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
  
)
"""

## Creation of df

# Using: list, tuple,set, dict, numpy,series...

In [4]:
# list
d = [10,20,30,40]
pd.DataFrame(d)

    0
0  10
1  20
2  30
3  40

In [5]:
pd.Series(d)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
# list of list
k = [[1,2],[3,4]]
k

[[1, 2], [3, 4]]

In [7]:
pd.DataFrame(k)

   0  1
0  1  2
1  3  4

In [8]:
# Lets change index and column name
pd.DataFrame(k,index=['A','B'],columns=['Data_1','Data_2'])

   Data_1  Data_2
A       1       2
B       3       4

In [14]:
# positional arguments
pd.DataFrame(k,['A','B'],['Data_1','Data_2'])

   Data_1  Data_2
A       1       2
B       3       4

In [17]:
# but if we interchange positions
print(pd.DataFrame([1,2,3],['A','B','C']))
print(pd.DataFrame(['A','B','C'],[1,2,3]))
#it will change output

   0
A  1
B  2
C  3
   0
1  A
2  B
3  C

In [ ]:
# create a df using a tuple
#Assignment

In [18]:
# it accepts homo. Hetro values
pd.DataFrame([10,23.4,'A','Amit'])

      0
0    10
1  23.4
2     A
3  Amit

In [19]:
# Using set
s = {(1,2,3),(1,2,5)}
# one tuple is one row
pd.DataFrame(s)

   0  1  2
0  1  2  3
1  1  2  5

In [20]:
# Using Dict
d = {'name':['Ashok','Seema'],'age':[23,24],'place':['pune','sangli']}
pd.DataFrame(d)
# key become a column label
# values will be added with respect to keys

    name  age   place
0  Ashok   23    pune
1  Seema   24  sangli

In [21]:
# Using Series
s = pd.Series([120,300,500,750])
pd.DataFrame(s)

     0
0  120
1  300
2  500
3  750

In [23]:
# Using numpy
import numpy as np
n = np.random.random(5)
pd.DataFrame(n)

          0
0  0.911371
1  0.482118
2  0.249262
3  0.350037
4  0.990707

In [24]:
# use 2D array to create a dataframe
n2 = np.random.random((5,4))
pd.DataFrame(n2)

          0         1         2         3
0  0.096541  0.005747  0.696970  0.053574
1  0.681191  0.628365  0.075086  0.558703
2  0.812332  0.772061  0.943294  0.306823
3  0.954004  0.396098  0.952134  0.645059
4  0.726763  0.676253  0.330319  0.874398

In [25]:
list('abcd')

['a', 'b', 'c', 'd']

In [26]:
# labeling the column
pd.DataFrame(n2,columns=list('abcd'))

          a         b         c         d
0  0.096541  0.005747  0.696970  0.053574
1  0.681191  0.628365  0.075086  0.558703
2  0.812332  0.772061  0.943294  0.306823
3  0.954004  0.396098  0.952134  0.645059
4  0.726763  0.676253  0.330319  0.874398

In [ ]:
# if we want to change index
#Assignment

In [27]:
# lets create a dataframe with different data types
d = {'Name':['A','V','D'],'Age':[23,45,60],'salary':[25.,45.,67.]}
d

{'Name': ['A', 'V', 'D'], 'Age': [23, 45, 60], 'salary': [25.0, 45.0, 67.0]}

In [28]:
new = pd.DataFrame(d)
new

  Name  Age  salary
0    A   23    25.0
1    V   45    45.0
2    D   60    67.0

In [29]:
#check data type of each column
new.dtypes

Name       object
Age         int64
salary    float64
dtype: object

# ----------------------------------------

In [30]:
#use name,age and salary dataframe
new

  Name  Age  salary
0    A   23    25.0
1    V   45    45.0
2    D   60    67.0

### Access a column

In [31]:
# Index:work default on columns
# acts a key
new

  Name  Age  salary
0    A   23    25.0
1    V   45    45.0
2    D   60    67.0

In [32]:
#access using . dot operator
new.Name

0    A
1    V
2    D
Name: Name, dtype: object

In [33]:
#use [] to access a single column with label
new['salary']

0    25.0
1    45.0
2    67.0
Name: salary, dtype: float64

In [44]:
# ACCESS MORE THAN ONE COLUMN
new[['Age','Name']]

   Age Name
0   23    A
1   45    V
2   60    D

# if i want to access multiple columns the use [[]]
# [] means one column:Series
# [[]]: means more than one columns: Df
# . dot operator access a single column

In [53]:
df = pd.DataFrame({'Data_1':[10,20,30,40]})
df

   Data_1
0      10
1      20
2      30
3      40

In [54]:
df.Data_1

0    10
1    20
2    30
3    40
Name: Data_1, dtype: int64