In [3]:
import pandas as pd

# pd.Series(data,index,dtype)

In [2]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
# if we want to customize index
pd.Series(data=[10,20,30,40,50],index=[101,102,103,104,105])

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [4]:
x = pd.Series(data=[10,20,30,40,50],index=[101,102,103,104,105])
x[103]

30

In [17]:
x[102:104] #CUSTOMIZED INDEXING WONT WORK IN SLICING

Series([], dtype: int64)

In [14]:
x

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [12]:
x[1:3]

102    20
103    30
dtype: int64

In [15]:
# check pandas version
import pandas
pandas.__version__

'1.3.4'

In [4]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [5]:
y = pd.Series(data=[10,20,30,40,50],index=list('abcde'))
y

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [19]:
#index
y['a']

10

In [20]:
y['a'::2]

a    10
c    30
e    50
dtype: int64

In [22]:
y['b':'d'] #stop is inclusive + customization of char index in possible

b    20
c    30
d    40
dtype: int64

## Check Properties of a series

In [23]:
x

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [24]:
x.ndim

1

In [25]:
type(x)

pandas.core.series.Series

In [26]:
x

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [27]:
#if we want to access only index
x.index

Int64Index([101, 102, 103, 104, 105], dtype='int64')

In [29]:
y.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [31]:
# if want to access values
x.values

array([10, 20, 30, 40, 50], dtype=int64)

In [32]:
# check total number of elements
x.size

5

In [34]:
x.shape

(5,)

In [36]:
#check data type
x.dtype

dtype('int64')

# DataFrame

In [ ]:
# 2D: row and column

In [38]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []

pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
)

In [39]:
pd.DataFrame().dtypes

Series([], dtype: object)

In [40]:
k = [12,34,56,67]
pd.DataFrame(k)

    0
0  12
1  34
2  56
3  67

In [41]:
pd.Series(k)

0    12
1    34
2    56
3    67
dtype: int64

# Q. What is difference between Series and DataFrame

### pd.DataFrame(data,index,columns,dtype)

In [42]:
pd.DataFrame([1,2,3,4])

   0
0  1
1  2
2  3
3  4

In [43]:
pd.DataFrame([1,2.,3,4])#implicit typecasting

     0
0  1.0
1  2.0
2  3.0
3  4.0

In [8]:
pd.DataFrame([1,2.,3,4],dtype='int') #explicite typecasting

   0
0  1
1  2
2  3
3  4

In [9]:
a = pd.DataFrame(['1','2','3'])
a

   0
0  1
1  2
2  3

In [10]:
a.dtypes

0    object
dtype: object

In [12]:
a2 = a.astype('int')
a2

   0
0  1
1  2
2  3

In [15]:
a2.dtypes

0    int32
dtype: object

In [16]:
a.astype('int16')

   0
0  1
1  2
2  3

In [18]:
a.astype('float16')

     0
0  1.0
1  2.0
2  3.0

### Biggest advantage is we can create a df with different data types

In [25]:
d ={'name':['A','B','C','D'],'age':[23,45,67,44],'salary':[24000.,45000,56000,78000]}

In [26]:
h = pd.DataFrame(d)
h

  name  age   salary
0    A   23  24000.0
1    B   45  45000.0
2    C   67  56000.0
3    D   44  78000.0

In [27]:
h.dtypes

name       object
age         int64
salary    float64
dtype: object

## We can create a df  using a 
- list
- Series
- numpy
- range
- str
- dict

In [28]:
pd.DataFrame([10,20,30])

    0
0  10
1  20
2  30

In [29]:
#list of list: one list is one row
pd.DataFrame([[10,20,30],[12,35,46]])

    0   1   2
0  10  20  30
1  12  35  46

In [30]:
#using Series
pd.DataFrame(pd.Series([101,102,103,104]))

     0
0  101
1  102
2  103
3  104

In [33]:
#list of Series
data = [pd.Series([101,102,103,104]),pd.Series([101,102,103,104]),pd.Series([101,102,103,104])]
data

[0    101
 1    102
 2    103
 3    104
 dtype: int64,
 0    101
 1    102
 2    103
 3    104
 dtype: int64,
 0    101
 1    102
 2    103
 3    104
 dtype: int64]

In [34]:
pd.DataFrame(data)

     0    1    2    3
0  101  102  103  104
1  101  102  103  104
2  101  102  103  104

In [38]:
#using numpy
import numpy as np
data2 = np.random.random((4,4))
data2

array([[0.1988049 , 0.71613034, 0.80136849, 0.59179263],
       [0.98998029, 0.94918537, 0.9993686 , 0.70877714],
       [0.43858942, 0.73641463, 0.47910808, 0.9455283 ],
       [0.38914443, 0.85261072, 0.76193258, 0.40876629]])

In [39]:
pd.DataFrame(data2)

          0         1         2         3
0  0.198805  0.716130  0.801368  0.591793
1  0.989980  0.949185  0.999369  0.708777
2  0.438589  0.736415  0.479108  0.945528
3  0.389144  0.852611  0.761933  0.408766

In [40]:
#customize column labels
pd.DataFrame(data2,columns=['val1','val2','val3','val4'])

       val1      val2      val3      val4
0  0.198805  0.716130  0.801368  0.591793
1  0.989980  0.949185  0.999369  0.708777
2  0.438589  0.736415  0.479108  0.945528
3  0.389144  0.852611  0.761933  0.408766

In [41]:
#using a dict
d

{'name': ['A', 'B', 'C', 'D'],
 'age': [23, 45, 67, 44],
 'salary': [24000.0, 45000, 56000, 78000]}

In [42]:
pd.DataFrame(d)

  name  age   salary
0    A   23  24000.0
1    B   45  45000.0
2    C   67  56000.0
3    D   44  78000.0