# Pandas

#### pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

### Pandas composed of 3 different data structures:
- Series [1 Dim]
- DataFrame [2 Dim]
- Panel [N-Dim][Combo of series and DataFrame ]

# Series

In [2]:
import pandas

In [3]:
pandas.__version__

'1.3.4'

In [4]:
import pandas as pd
pd.__version__

'1.3.4'

In [5]:
# create an empty series
pd.Series()

C:\Users\hakim\AppData\Local\Temp/ipykernel_10024/3236373807.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()

Series([], dtype: float64)

In [6]:
pd.Series(dtype='object')
# object dtype means: u have str data/hetrogeneous data

Series([], dtype: object)

## Strcuture of Series
### pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    )

# Features of Series

In [ ]:
# It is cobination of 3 things
- Data/values
- Index
- dtype

In [17]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [16]:
pd.Series(['10','20','30','40','50'])

0    10
1    20
2    30
3    40
4    50
dtype: object

In [9]:
#Hetro data
pd.Series([10,20.88,'30','40','50'])

0       10
1    20.88
2       30
3       40
4       50
dtype: object

In [ ]:
# It can accept homo. and hetro. data
# homo

In [ ]:
# when we supply hetro. data or str data then dtype is object

In [18]:
# supply all str data
pd.Series(['Ramesh','Suresh','Dinesh'])

0    Ramesh
1    Suresh
2    Dinesh
dtype: object

In [ ]:
# Difference between int32(4 bytes) and int64(8 bytes)
# 8 bit ==> 1 byte

In [19]:
a = pd.Series([10,20,30,40,50])
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [20]:
a.__sizeof__()

168

In [21]:
b = pd.Series([10,20,30,40,50],dtype='int8')
b

0    10
1    20
2    30
3    40
4    50
dtype: int8

In [22]:
b.__sizeof__()

133

In [23]:
# background data structure is an array
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [24]:
# indexing is possible
# access 40
a[3]

40

In [25]:
a[4]

50

In [26]:
a[-1] # in series -ve indexing is nt allowed

KeyError: -1

In [27]:
# Is direct item assignment is possible??
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
a[2] #replace 30 by 300

30

In [29]:
id(a)

2153872382224

In [30]:
a[2] = 300

In [31]:
a

0     10
1     20
2    300
3     40
4     50
dtype: int64

In [32]:
id(a)

2153872382224

In [33]:
pd.Series([12132312312332,123123454354646546546])

0           12132312312332
1    123123454354646546546
dtype: object

# After the change,id doesnt change and changes persist in the same object
# hence Series is a mutable data struture

In [34]:
# slicing supported
a[:]

0     10
1     20
2    300
3     40
4     50
dtype: int64

In [35]:
#access 300,40,50
a[2:]

2    300
3     40
4     50
dtype: int64

In [37]:
#10,300,50
a[::2]

0     10
2    300
4     50
dtype: int64

In [39]:
# replace 20,300,40 by 2,3,4 resp.
a[1:4]

1     20
2    300
3     40
dtype: int64

In [40]:
a[1:4] = [2,3,4]

In [41]:
a

0    10
1     2
2     3
3     4
4    50
dtype: int64

In [43]:
# replace 10 and 50 by 0
a[::4] = 0

In [44]:
a

0    0
1    2
2    3
3    4
4    0
dtype: int64

In [46]:
# if we want to add multiple values at same position then we cant add
a[0] = 1,2,3

ValueError: setting an array element with a sequence.

In [47]:
a[0] = [1,2,3]

ValueError: setting an array element with a sequence.

### Manipulation of index

In [48]:
import numpy as np
s = pd.Series(np.arange(101,111))
s

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
dtype: int32

In [49]:
# if we wnt to access only data
s.values
#returns an array of value

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [50]:
# access index
s.index

RangeIndex(start=0, stop=10, step=1)

In [51]:
# check dtype
s.dtype

dtype('int32')

In [52]:
# check dim
s.ndim

1

In [53]:
#check total number of elements
s.size

10

In [54]:
s.shape

(10,)

In [55]:
len(s)

10

In [57]:
# now lets see Index manipulation
s = pd.Series(data=np.arange(101,111),index=range(10,20))
s

10    101
11    102
12    103
13    104
14    105
15    106
16    107
17    108
18    109
19    110
dtype: int32

In [58]:
s[10]

101

In [59]:
s[19]

110

In [60]:
s[17:]

Series([], dtype: int32)

In [61]:
s[7:]

17    108
18    109
19    110
dtype: int32

In [63]:
# scalar series: 10 customers with same bank_name
pd.Series('BOI',index=range(10))

0    BOI
1    BOI
2    BOI
3    BOI
4    BOI
5    BOI
6    BOI
7    BOI
8    BOI
9    BOI
dtype: object

In [66]:
nm = pd.Series('BOI',index=range(3))
nm

0    BOI
1    BOI
2    BOI
dtype: object

In [67]:
ac = pd.Series([12234,45646,67686])
ac

0    12234
1    45646
2    67686
dtype: int64

In [68]:
pd.DataFrame([ac,nm])

       0      1      2
0  12234  45646  67686
1    BOI    BOI    BOI

In [74]:
pd.concat([ac,nm],axis=1)

       0    1
0  12234  BOI
1  45646  BOI
2  67686  BOI

## Lets create a series of a string and do the data analysis

In [ ]:
n = pd.Series([])
n

#### to do analysis we need questions??

In [ ]:
# fetch employee with inital letter P

In [ ]:
# we can use boolean output as an input in index

In [ ]:
# convert names in upper case

In [ ]:
# sort in alphabatic order

In [ ]:
#in descending order

In [ ]:
# create a series which wil have length of each name